# R
set_property PACKAGE_PIN G6 [get_ports led[0]]
set_property PACKAGE_PIN G3 [get_ports led[1]]
set_property PACKAGE_PIN J3 [get_ports led[2]]
set_property PACKAGE_PIN K1 [get_ports led[3]]
# G
set_property PACKAGE_PIN F6 [get_ports led[4]]
set_property PACKAGE_PIN J4 [get_ports led[5]]
set_property PACKAGE_PIN J2 [get_ports led[6]]
set_property PACKAGE_PIN H6 [get_ports led[7]]
# B
set_property PACKAGE_PIN E1 [get_ports led[8]]
set_property PACKAGE_PIN G4 [get_ports led[9]]
set_property PACKAGE_PIN H4 [get_ports led[10]]
set_property PACKAGE_PIN K2 [get_ports led[11]]

set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports led[11]]

set_property PACKAGE_PIN E3 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
