# arty 100 MHz CLK
set_property LOC E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property LOC T10 [get_ports stb]
set_property IOSTANDARD LVCMOS33 [get_ports stb]
set_property LOC A10 [get_ports di]
set_property IOSTANDARD LVCMOS33 [get_ports di]
set_property LOC T9 [get_ports do]
set_property IOSTANDARD LVCMOS33 [get_ports do]
