//--------------------------------------------------------------------------------
// Auto-generated by Migen (7507a2b) & LiteX (f7a256bc) on 2021-10-28 14:58:20
//--------------------------------------------------------------------------------
module top(
	input wire serial_rx,
	output reg serial_tx,
	input wire gsrn,
	output reg user_led0,
	output reg user_led1,
	output reg user_led2,
	output reg user_led3,
	output reg user_led4,
	output reg user_led5,
	output reg user_led6,
	output reg user_led7,
	output reg user_led8,
	output reg user_led9,
	output reg user_led10,
	output reg user_led11,
	output reg user_led12,
	output reg user_led13
);

reg main_basesoc_soc_rst = 1'd0;
wire main_basesoc_cpu_rst;
reg [1:0] main_basesoc_reset_storage = 2'd0;
reg main_basesoc_reset_re = 1'd0;
reg [31:0] main_basesoc_scratch_storage = 32'd305419896;
reg main_basesoc_scratch_re = 1'd0;
wire [31:0] main_basesoc_bus_errors_status;
wire main_basesoc_bus_errors_we;
reg main_basesoc_bus_errors_re = 1'd0;
wire main_basesoc_bus_error;
reg [31:0] main_basesoc_bus_errors = 32'd0;
wire main_basesoc_reset;
reg [31:0] main_basesoc_interrupt = 32'd0;
wire [29:0] main_basesoc_ibus_adr;
wire [31:0] main_basesoc_ibus_dat_w;
wire [31:0] main_basesoc_ibus_dat_r;
wire [3:0] main_basesoc_ibus_sel;
wire main_basesoc_ibus_cyc;
wire main_basesoc_ibus_stb;
wire main_basesoc_ibus_ack;
wire main_basesoc_ibus_we;
wire [2:0] main_basesoc_ibus_cti;
wire [1:0] main_basesoc_ibus_bte;
wire main_basesoc_ibus_err;
wire [29:0] main_basesoc_dbus_adr;
wire [31:0] main_basesoc_dbus_dat_w;
wire [31:0] main_basesoc_dbus_dat_r;
wire [3:0] main_basesoc_dbus_sel;
wire main_basesoc_dbus_cyc;
wire main_basesoc_dbus_stb;
wire main_basesoc_dbus_ack;
wire main_basesoc_dbus_we;
wire [2:0] main_basesoc_dbus_cti;
wire [1:0] main_basesoc_dbus_bte;
wire main_basesoc_dbus_err;
reg [31:0] main_basesoc_vexriscv = 32'd0;
wire [29:0] main_basesoc_ram_bus_adr;
wire [31:0] main_basesoc_ram_bus_dat_w;
wire [31:0] main_basesoc_ram_bus_dat_r;
wire [3:0] main_basesoc_ram_bus_sel;
wire main_basesoc_ram_bus_cyc;
wire main_basesoc_ram_bus_stb;
reg main_basesoc_ram_bus_ack = 1'd0;
wire main_basesoc_ram_bus_we;
wire [2:0] main_basesoc_ram_bus_cti;
wire [1:0] main_basesoc_ram_bus_bte;
reg main_basesoc_ram_bus_err = 1'd0;
wire [14:0] main_basesoc_adr;
wire [31:0] main_basesoc_dat_r;
wire main_basesoc_tx_sink_valid;
reg main_basesoc_tx_sink_ready = 1'd0;
wire main_basesoc_tx_sink_first;
wire main_basesoc_tx_sink_last;
wire [7:0] main_basesoc_tx_sink_payload_data;
reg [7:0] main_basesoc_tx_data = 8'd0;
reg [3:0] main_basesoc_tx_count = 4'd0;
reg main_basesoc_tx_enable = 1'd0;
reg main_basesoc_tx_tick = 1'd0;
reg [31:0] main_basesoc_tx_phase = 32'd0;
reg main_basesoc_rx_source_valid = 1'd0;
wire main_basesoc_rx_source_ready;
reg main_basesoc_rx_source_first = 1'd0;
reg main_basesoc_rx_source_last = 1'd0;
reg [7:0] main_basesoc_rx_source_payload_data = 8'd0;
reg [7:0] main_basesoc_rx_data = 8'd0;
reg [3:0] main_basesoc_rx_count = 4'd0;
reg main_basesoc_rx_enable = 1'd0;
reg main_basesoc_rx_tick = 1'd0;
reg [31:0] main_basesoc_rx_phase = 32'd0;
wire main_basesoc_rx_rx;
reg main_basesoc_rx_rx_d = 1'd0;
reg main_basesoc_uart_rxtx_re = 1'd0;
wire [7:0] main_basesoc_uart_rxtx_r;
reg main_basesoc_uart_rxtx_we = 1'd0;
wire [7:0] main_basesoc_uart_rxtx_w;
wire main_basesoc_uart_txfull_status;
wire main_basesoc_uart_txfull_we;
reg main_basesoc_uart_txfull_re = 1'd0;
wire main_basesoc_uart_rxempty_status;
wire main_basesoc_uart_rxempty_we;
reg main_basesoc_uart_rxempty_re = 1'd0;
wire main_basesoc_uart_irq;
wire main_basesoc_uart_tx_status;
reg main_basesoc_uart_tx_pending = 1'd0;
wire main_basesoc_uart_tx_trigger;
reg main_basesoc_uart_tx_clear = 1'd0;
reg main_basesoc_uart_tx_trigger_d = 1'd0;
wire main_basesoc_uart_rx_status;
reg main_basesoc_uart_rx_pending = 1'd0;
wire main_basesoc_uart_rx_trigger;
reg main_basesoc_uart_rx_clear = 1'd0;
reg main_basesoc_uart_rx_trigger_d = 1'd0;
wire main_basesoc_uart_tx0;
wire main_basesoc_uart_rx0;
reg [1:0] main_basesoc_uart_status_status = 2'd0;
wire main_basesoc_uart_status_we;
reg main_basesoc_uart_status_re = 1'd0;
wire main_basesoc_uart_tx1;
wire main_basesoc_uart_rx1;
reg [1:0] main_basesoc_uart_pending_status = 2'd0;
wire main_basesoc_uart_pending_we;
reg main_basesoc_uart_pending_re = 1'd0;
reg [1:0] main_basesoc_uart_pending_r = 2'd0;
wire main_basesoc_uart_tx2;
wire main_basesoc_uart_rx2;
reg [1:0] main_basesoc_uart_enable_storage = 2'd0;
reg main_basesoc_uart_enable_re = 1'd0;
wire main_basesoc_uart_txempty_status;
wire main_basesoc_uart_txempty_we;
reg main_basesoc_uart_txempty_re = 1'd0;
wire main_basesoc_uart_rxfull_status;
wire main_basesoc_uart_rxfull_we;
reg main_basesoc_uart_rxfull_re = 1'd0;
wire main_basesoc_uart_uart_sink_valid;
wire main_basesoc_uart_uart_sink_ready;
wire main_basesoc_uart_uart_sink_first;
wire main_basesoc_uart_uart_sink_last;
wire [7:0] main_basesoc_uart_uart_sink_payload_data;
wire main_basesoc_uart_uart_source_valid;
wire main_basesoc_uart_uart_source_ready;
wire main_basesoc_uart_uart_source_first;
wire main_basesoc_uart_uart_source_last;
wire [7:0] main_basesoc_uart_uart_source_payload_data;
wire main_basesoc_uart_tx_fifo_sink_valid;
wire main_basesoc_uart_tx_fifo_sink_ready;
reg main_basesoc_uart_tx_fifo_sink_first = 1'd0;
reg main_basesoc_uart_tx_fifo_sink_last = 1'd0;
wire [7:0] main_basesoc_uart_tx_fifo_sink_payload_data;
wire main_basesoc_uart_tx_fifo_source_valid;
wire main_basesoc_uart_tx_fifo_source_ready;
wire main_basesoc_uart_tx_fifo_source_first;
wire main_basesoc_uart_tx_fifo_source_last;
wire [7:0] main_basesoc_uart_tx_fifo_source_payload_data;
wire main_basesoc_uart_tx_fifo_re;
reg main_basesoc_uart_tx_fifo_readable = 1'd0;
wire main_basesoc_uart_tx_fifo_syncfifo_we;
wire main_basesoc_uart_tx_fifo_syncfifo_writable;
wire main_basesoc_uart_tx_fifo_syncfifo_re;
wire main_basesoc_uart_tx_fifo_syncfifo_readable;
wire [9:0] main_basesoc_uart_tx_fifo_syncfifo_din;
wire [9:0] main_basesoc_uart_tx_fifo_syncfifo_dout;
reg [4:0] main_basesoc_uart_tx_fifo_level0 = 5'd0;
reg main_basesoc_uart_tx_fifo_replace = 1'd0;
reg [3:0] main_basesoc_uart_tx_fifo_produce = 4'd0;
reg [3:0] main_basesoc_uart_tx_fifo_consume = 4'd0;
reg [3:0] main_basesoc_uart_tx_fifo_wrport_adr = 4'd0;
wire [9:0] main_basesoc_uart_tx_fifo_wrport_dat_r;
wire main_basesoc_uart_tx_fifo_wrport_we;
wire [9:0] main_basesoc_uart_tx_fifo_wrport_dat_w;
wire main_basesoc_uart_tx_fifo_do_read;
wire [3:0] main_basesoc_uart_tx_fifo_rdport_adr;
wire [9:0] main_basesoc_uart_tx_fifo_rdport_dat_r;
wire main_basesoc_uart_tx_fifo_rdport_re;
wire [4:0] main_basesoc_uart_tx_fifo_level1;
wire [7:0] main_basesoc_uart_tx_fifo_fifo_in_payload_data;
wire main_basesoc_uart_tx_fifo_fifo_in_first;
wire main_basesoc_uart_tx_fifo_fifo_in_last;
wire [7:0] main_basesoc_uart_tx_fifo_fifo_out_payload_data;
wire main_basesoc_uart_tx_fifo_fifo_out_first;
wire main_basesoc_uart_tx_fifo_fifo_out_last;
wire main_basesoc_uart_rx_fifo_sink_valid;
wire main_basesoc_uart_rx_fifo_sink_ready;
wire main_basesoc_uart_rx_fifo_sink_first;
wire main_basesoc_uart_rx_fifo_sink_last;
wire [7:0] main_basesoc_uart_rx_fifo_sink_payload_data;
wire main_basesoc_uart_rx_fifo_source_valid;
wire main_basesoc_uart_rx_fifo_source_ready;
wire main_basesoc_uart_rx_fifo_source_first;
wire main_basesoc_uart_rx_fifo_source_last;
wire [7:0] main_basesoc_uart_rx_fifo_source_payload_data;
wire main_basesoc_uart_rx_fifo_re;
reg main_basesoc_uart_rx_fifo_readable = 1'd0;
wire main_basesoc_uart_rx_fifo_syncfifo_we;
wire main_basesoc_uart_rx_fifo_syncfifo_writable;
wire main_basesoc_uart_rx_fifo_syncfifo_re;
wire main_basesoc_uart_rx_fifo_syncfifo_readable;
wire [9:0] main_basesoc_uart_rx_fifo_syncfifo_din;
wire [9:0] main_basesoc_uart_rx_fifo_syncfifo_dout;
reg [4:0] main_basesoc_uart_rx_fifo_level0 = 5'd0;
reg main_basesoc_uart_rx_fifo_replace = 1'd0;
reg [3:0] main_basesoc_uart_rx_fifo_produce = 4'd0;
reg [3:0] main_basesoc_uart_rx_fifo_consume = 4'd0;
reg [3:0] main_basesoc_uart_rx_fifo_wrport_adr = 4'd0;
wire [9:0] main_basesoc_uart_rx_fifo_wrport_dat_r;
wire main_basesoc_uart_rx_fifo_wrport_we;
wire [9:0] main_basesoc_uart_rx_fifo_wrport_dat_w;
wire main_basesoc_uart_rx_fifo_do_read;
wire [3:0] main_basesoc_uart_rx_fifo_rdport_adr;
wire [9:0] main_basesoc_uart_rx_fifo_rdport_dat_r;
wire main_basesoc_uart_rx_fifo_rdport_re;
wire [4:0] main_basesoc_uart_rx_fifo_level1;
wire [7:0] main_basesoc_uart_rx_fifo_fifo_in_payload_data;
wire main_basesoc_uart_rx_fifo_fifo_in_first;
wire main_basesoc_uart_rx_fifo_fifo_in_last;
wire [7:0] main_basesoc_uart_rx_fifo_fifo_out_payload_data;
wire main_basesoc_uart_rx_fifo_fifo_out_first;
wire main_basesoc_uart_rx_fifo_fifo_out_last;
reg [31:0] main_basesoc_timer_load_storage = 32'd0;
reg main_basesoc_timer_load_re = 1'd0;
reg [31:0] main_basesoc_timer_reload_storage = 32'd0;
reg main_basesoc_timer_reload_re = 1'd0;
reg main_basesoc_timer_en_storage = 1'd0;
reg main_basesoc_timer_en_re = 1'd0;
reg main_basesoc_timer_update_value_storage = 1'd0;
reg main_basesoc_timer_update_value_re = 1'd0;
reg [31:0] main_basesoc_timer_value_status = 32'd0;
wire main_basesoc_timer_value_we;
reg main_basesoc_timer_value_re = 1'd0;
wire main_basesoc_timer_irq;
wire main_basesoc_timer_zero_status;
reg main_basesoc_timer_zero_pending = 1'd0;
wire main_basesoc_timer_zero_trigger;
reg main_basesoc_timer_zero_clear = 1'd0;
reg main_basesoc_timer_zero_trigger_d = 1'd0;
wire main_basesoc_timer_zero0;
wire main_basesoc_timer_status_status;
wire main_basesoc_timer_status_we;
reg main_basesoc_timer_status_re = 1'd0;
wire main_basesoc_timer_zero1;
wire main_basesoc_timer_pending_status;
wire main_basesoc_timer_pending_we;
reg main_basesoc_timer_pending_re = 1'd0;
reg main_basesoc_timer_pending_r = 1'd0;
wire main_basesoc_timer_zero2;
reg main_basesoc_timer_enable_storage = 1'd0;
reg main_basesoc_timer_enable_re = 1'd0;
reg [31:0] main_basesoc_timer_value = 32'd0;
wire por_clk;
wire por_rst;
wire sys_clk;
wire sys_rst;
wire main_crg_clkout;
reg [15:0] main_crg_por_count = 16'd65535;
wire main_crg_por_done;
reg main_crg_reset = 1'd0;
wire main_crg_locked;
wire main_crg_clkin;
wire [29:0] main_bus_adr;
wire [31:0] main_bus_dat_w;
reg [31:0] main_bus_dat_r = 32'd0;
wire [3:0] main_bus_sel;
wire main_bus_cyc;
wire main_bus_stb;
reg main_bus_ack = 1'd0;
wire main_bus_we;
wire [2:0] main_bus_cti;
wire [1:0] main_bus_bte;
reg main_bus_err = 1'd0;
wire [31:0] main_datain0;
wire [31:0] main_dataout0;
reg main_cs0 = 1'd0;
reg main_wren0 = 1'd0;
wire [31:0] main_datain1;
wire [31:0] main_dataout1;
reg main_cs1 = 1'd0;
reg main_wren1 = 1'd0;
reg [13:0] main_storage = 14'd0;
reg main_re = 1'd0;
reg [13:0] main_chaser = 14'd0;
reg main_mode = 1'd0;
wire main_wait;
wire main_done;
reg [21:0] main_count = 22'd2678571;
reg builder_rs232phytx_state = 1'd0;
reg builder_rs232phytx_next_state = 1'd0;
reg [3:0] main_basesoc_tx_count_rs232phytx_next_value0 = 4'd0;
reg main_basesoc_tx_count_rs232phytx_next_value_ce0 = 1'd0;
reg main_basesoc_serial_tx_rs232phytx_next_value1 = 1'd0;
reg main_basesoc_serial_tx_rs232phytx_next_value_ce1 = 1'd0;
reg [7:0] main_basesoc_tx_data_rs232phytx_next_value2 = 8'd0;
reg main_basesoc_tx_data_rs232phytx_next_value_ce2 = 1'd0;
reg builder_rs232phyrx_state = 1'd0;
reg builder_rs232phyrx_next_state = 1'd0;
reg [3:0] main_basesoc_rx_count_rs232phyrx_next_value0 = 4'd0;
reg main_basesoc_rx_count_rs232phyrx_next_value_ce0 = 1'd0;
reg [7:0] main_basesoc_rx_data_rs232phyrx_next_value1 = 8'd0;
reg main_basesoc_rx_data_rs232phyrx_next_value_ce1 = 1'd0;
wire builder_clkfb;
reg [13:0] builder_basesoc_adr = 14'd0;
reg builder_basesoc_we = 1'd0;
reg [31:0] builder_basesoc_dat_w = 32'd0;
wire [31:0] builder_basesoc_dat_r;
wire [29:0] builder_basesoc_wishbone_adr;
wire [31:0] builder_basesoc_wishbone_dat_w;
reg [31:0] builder_basesoc_wishbone_dat_r = 32'd0;
wire [3:0] builder_basesoc_wishbone_sel;
wire builder_basesoc_wishbone_cyc;
wire builder_basesoc_wishbone_stb;
reg builder_basesoc_wishbone_ack = 1'd0;
wire builder_basesoc_wishbone_we;
wire [2:0] builder_basesoc_wishbone_cti;
wire [1:0] builder_basesoc_wishbone_bte;
reg builder_basesoc_wishbone_err = 1'd0;
wire [29:0] builder_shared_adr;
wire [31:0] builder_shared_dat_w;
reg [31:0] builder_shared_dat_r = 32'd0;
wire [3:0] builder_shared_sel;
wire builder_shared_cyc;
wire builder_shared_stb;
reg builder_shared_ack = 1'd0;
wire builder_shared_we;
wire [2:0] builder_shared_cti;
wire [1:0] builder_shared_bte;
wire builder_shared_err;
wire [1:0] builder_request;
reg builder_grant = 1'd0;
reg [2:0] builder_slave_sel = 3'd0;
reg [2:0] builder_slave_sel_r = 3'd0;
reg builder_error = 1'd0;
wire builder_wait;
wire builder_done;
reg [19:0] builder_count = 20'd1000000;
wire [13:0] builder_csr_bankarray_interface0_bank_bus_adr;
wire builder_csr_bankarray_interface0_bank_bus_we;
wire [31:0] builder_csr_bankarray_interface0_bank_bus_dat_w;
reg [31:0] builder_csr_bankarray_interface0_bank_bus_dat_r = 32'd0;
reg builder_csr_bankarray_csrbank0_reset0_re = 1'd0;
wire [1:0] builder_csr_bankarray_csrbank0_reset0_r;
reg builder_csr_bankarray_csrbank0_reset0_we = 1'd0;
wire [1:0] builder_csr_bankarray_csrbank0_reset0_w;
reg builder_csr_bankarray_csrbank0_scratch0_re = 1'd0;
wire [31:0] builder_csr_bankarray_csrbank0_scratch0_r;
reg builder_csr_bankarray_csrbank0_scratch0_we = 1'd0;
wire [31:0] builder_csr_bankarray_csrbank0_scratch0_w;
reg builder_csr_bankarray_csrbank0_bus_errors_re = 1'd0;
wire [31:0] builder_csr_bankarray_csrbank0_bus_errors_r;
reg builder_csr_bankarray_csrbank0_bus_errors_we = 1'd0;
wire [31:0] builder_csr_bankarray_csrbank0_bus_errors_w;
wire builder_csr_bankarray_csrbank0_sel;
wire [13:0] builder_csr_bankarray_sram_bus_adr;
wire builder_csr_bankarray_sram_bus_we;
wire [31:0] builder_csr_bankarray_sram_bus_dat_w;
reg [31:0] builder_csr_bankarray_sram_bus_dat_r = 32'd0;
wire [5:0] builder_csr_bankarray_adr;
wire [7:0] builder_csr_bankarray_dat_r;
wire builder_csr_bankarray_sel;
reg builder_csr_bankarray_sel_r = 1'd0;
wire [13:0] builder_csr_bankarray_interface1_bank_bus_adr;
wire builder_csr_bankarray_interface1_bank_bus_we;
wire [31:0] builder_csr_bankarray_interface1_bank_bus_dat_w;
reg [31:0] builder_csr_bankarray_interface1_bank_bus_dat_r = 32'd0;
reg builder_csr_bankarray_csrbank1_out0_re = 1'd0;
wire [13:0] builder_csr_bankarray_csrbank1_out0_r;
reg builder_csr_bankarray_csrbank1_out0_we = 1'd0;
wire [13:0] builder_csr_bankarray_csrbank1_out0_w;
wire builder_csr_bankarray_csrbank1_sel;
wire [13:0] builder_csr_bankarray_interface2_bank_bus_adr;
wire builder_csr_bankarray_interface2_bank_bus_we;
wire [31:0] builder_csr_bankarray_interface2_bank_bus_dat_w;
reg [31:0] builder_csr_bankarray_interface2_bank_bus_dat_r = 32'd0;
reg builder_csr_bankarray_csrbank2_load0_re = 1'd0;
wire [31:0] builder_csr_bankarray_csrbank2_load0_r;
reg builder_csr_bankarray_csrbank2_load0_we = 1'd0;
wire [31:0] builder_csr_bankarray_csrbank2_load0_w;
reg builder_csr_bankarray_csrbank2_reload0_re = 1'd0;
wire [31:0] builder_csr_bankarray_csrbank2_reload0_r;
reg builder_csr_bankarray_csrbank2_reload0_we = 1'd0;
wire [31:0] builder_csr_bankarray_csrbank2_reload0_w;
reg builder_csr_bankarray_csrbank2_en0_re = 1'd0;
wire builder_csr_bankarray_csrbank2_en0_r;
reg builder_csr_bankarray_csrbank2_en0_we = 1'd0;
wire builder_csr_bankarray_csrbank2_en0_w;
reg builder_csr_bankarray_csrbank2_update_value0_re = 1'd0;
wire builder_csr_bankarray_csrbank2_update_value0_r;
reg builder_csr_bankarray_csrbank2_update_value0_we = 1'd0;
wire builder_csr_bankarray_csrbank2_update_value0_w;
reg builder_csr_bankarray_csrbank2_value_re = 1'd0;
wire [31:0] builder_csr_bankarray_csrbank2_value_r;
reg builder_csr_bankarray_csrbank2_value_we = 1'd0;
wire [31:0] builder_csr_bankarray_csrbank2_value_w;
reg builder_csr_bankarray_csrbank2_ev_status_re = 1'd0;
wire builder_csr_bankarray_csrbank2_ev_status_r;
reg builder_csr_bankarray_csrbank2_ev_status_we = 1'd0;
wire builder_csr_bankarray_csrbank2_ev_status_w;
reg builder_csr_bankarray_csrbank2_ev_pending_re = 1'd0;
wire builder_csr_bankarray_csrbank2_ev_pending_r;
reg builder_csr_bankarray_csrbank2_ev_pending_we = 1'd0;
wire builder_csr_bankarray_csrbank2_ev_pending_w;
reg builder_csr_bankarray_csrbank2_ev_enable0_re = 1'd0;
wire builder_csr_bankarray_csrbank2_ev_enable0_r;
reg builder_csr_bankarray_csrbank2_ev_enable0_we = 1'd0;
wire builder_csr_bankarray_csrbank2_ev_enable0_w;
wire builder_csr_bankarray_csrbank2_sel;
wire [13:0] builder_csr_bankarray_interface3_bank_bus_adr;
wire builder_csr_bankarray_interface3_bank_bus_we;
wire [31:0] builder_csr_bankarray_interface3_bank_bus_dat_w;
reg [31:0] builder_csr_bankarray_interface3_bank_bus_dat_r = 32'd0;
reg builder_csr_bankarray_csrbank3_txfull_re = 1'd0;
wire builder_csr_bankarray_csrbank3_txfull_r;
reg builder_csr_bankarray_csrbank3_txfull_we = 1'd0;
wire builder_csr_bankarray_csrbank3_txfull_w;
reg builder_csr_bankarray_csrbank3_rxempty_re = 1'd0;
wire builder_csr_bankarray_csrbank3_rxempty_r;
reg builder_csr_bankarray_csrbank3_rxempty_we = 1'd0;
wire builder_csr_bankarray_csrbank3_rxempty_w;
reg builder_csr_bankarray_csrbank3_ev_status_re = 1'd0;
wire [1:0] builder_csr_bankarray_csrbank3_ev_status_r;
reg builder_csr_bankarray_csrbank3_ev_status_we = 1'd0;
wire [1:0] builder_csr_bankarray_csrbank3_ev_status_w;
reg builder_csr_bankarray_csrbank3_ev_pending_re = 1'd0;
wire [1:0] builder_csr_bankarray_csrbank3_ev_pending_r;
reg builder_csr_bankarray_csrbank3_ev_pending_we = 1'd0;
wire [1:0] builder_csr_bankarray_csrbank3_ev_pending_w;
reg builder_csr_bankarray_csrbank3_ev_enable0_re = 1'd0;
wire [1:0] builder_csr_bankarray_csrbank3_ev_enable0_r;
reg builder_csr_bankarray_csrbank3_ev_enable0_we = 1'd0;
wire [1:0] builder_csr_bankarray_csrbank3_ev_enable0_w;
reg builder_csr_bankarray_csrbank3_txempty_re = 1'd0;
wire builder_csr_bankarray_csrbank3_txempty_r;
reg builder_csr_bankarray_csrbank3_txempty_we = 1'd0;
wire builder_csr_bankarray_csrbank3_txempty_w;
reg builder_csr_bankarray_csrbank3_rxfull_re = 1'd0;
wire builder_csr_bankarray_csrbank3_rxfull_r;
reg builder_csr_bankarray_csrbank3_rxfull_we = 1'd0;
wire builder_csr_bankarray_csrbank3_rxfull_w;
wire builder_csr_bankarray_csrbank3_sel;
wire [13:0] builder_csr_interconnect_adr;
wire builder_csr_interconnect_we;
wire [31:0] builder_csr_interconnect_dat_w;
wire [31:0] builder_csr_interconnect_dat_r;
reg builder_state = 1'd0;
reg builder_next_state = 1'd0;
reg [29:0] builder_array_muxed0 = 30'd0;
reg [31:0] builder_array_muxed1 = 32'd0;
reg [3:0] builder_array_muxed2 = 4'd0;
reg builder_array_muxed3 = 1'd0;
reg builder_array_muxed4 = 1'd0;
reg builder_array_muxed5 = 1'd0;
reg [2:0] builder_array_muxed6 = 3'd0;
reg [1:0] builder_array_muxed7 = 2'd0;
reg builder_regs0 = 1'd0;
reg builder_regs1 = 1'd0;
wire builder_rst10;
wire builder_rst11;

assign main_basesoc_reset = (main_basesoc_soc_rst | main_basesoc_cpu_rst);
assign main_basesoc_bus_error = builder_error;
always @(*) begin
	main_basesoc_interrupt <= 32'd0;
	main_basesoc_interrupt[1] <= main_basesoc_timer_irq;
	main_basesoc_interrupt[0] <= main_basesoc_uart_irq;
end
assign main_basesoc_bus_errors_status = main_basesoc_bus_errors;
assign main_basesoc_adr = main_basesoc_ram_bus_adr[14:0];
assign main_basesoc_ram_bus_dat_r = main_basesoc_dat_r;
always @(*) begin
	builder_rs232phytx_next_state <= 1'd0;
	main_basesoc_tx_count_rs232phytx_next_value0 <= 4'd0;
	main_basesoc_tx_count_rs232phytx_next_value_ce0 <= 1'd0;
	main_basesoc_serial_tx_rs232phytx_next_value1 <= 1'd0;
	main_basesoc_serial_tx_rs232phytx_next_value_ce1 <= 1'd0;
	main_basesoc_tx_sink_ready <= 1'd0;
	main_basesoc_tx_data_rs232phytx_next_value2 <= 8'd0;
	main_basesoc_tx_data_rs232phytx_next_value_ce2 <= 1'd0;
	main_basesoc_tx_enable <= 1'd0;
	builder_rs232phytx_next_state <= builder_rs232phytx_state;
	case (builder_rs232phytx_state)
		1'd1: begin
			main_basesoc_tx_enable <= 1'd1;
			if (main_basesoc_tx_tick) begin
				main_basesoc_serial_tx_rs232phytx_next_value1 <= main_basesoc_tx_data;
				main_basesoc_serial_tx_rs232phytx_next_value_ce1 <= 1'd1;
				main_basesoc_tx_count_rs232phytx_next_value0 <= (main_basesoc_tx_count + 1'd1);
				main_basesoc_tx_count_rs232phytx_next_value_ce0 <= 1'd1;
				main_basesoc_tx_data_rs232phytx_next_value2 <= {1'd1, main_basesoc_tx_data[7:1]};
				main_basesoc_tx_data_rs232phytx_next_value_ce2 <= 1'd1;
				if ((main_basesoc_tx_count == 4'd9)) begin
					main_basesoc_tx_sink_ready <= 1'd1;
					builder_rs232phytx_next_state <= 1'd0;
				end
			end
		end
		default: begin
			main_basesoc_tx_count_rs232phytx_next_value0 <= 1'd0;
			main_basesoc_tx_count_rs232phytx_next_value_ce0 <= 1'd1;
			main_basesoc_serial_tx_rs232phytx_next_value1 <= 1'd1;
			main_basesoc_serial_tx_rs232phytx_next_value_ce1 <= 1'd1;
			if (main_basesoc_tx_sink_valid) begin
				main_basesoc_serial_tx_rs232phytx_next_value1 <= 1'd0;
				main_basesoc_serial_tx_rs232phytx_next_value_ce1 <= 1'd1;
				main_basesoc_tx_data_rs232phytx_next_value2 <= main_basesoc_tx_sink_payload_data;
				main_basesoc_tx_data_rs232phytx_next_value_ce2 <= 1'd1;
				builder_rs232phytx_next_state <= 1'd1;
			end
		end
	endcase
end
always @(*) begin
	builder_rs232phyrx_next_state <= 1'd0;
	main_basesoc_rx_count_rs232phyrx_next_value0 <= 4'd0;
	main_basesoc_rx_count_rs232phyrx_next_value_ce0 <= 1'd0;
	main_basesoc_rx_source_valid <= 1'd0;
	main_basesoc_rx_data_rs232phyrx_next_value1 <= 8'd0;
	main_basesoc_rx_data_rs232phyrx_next_value_ce1 <= 1'd0;
	main_basesoc_rx_source_payload_data <= 8'd0;
	main_basesoc_rx_enable <= 1'd0;
	builder_rs232phyrx_next_state <= builder_rs232phyrx_state;
	case (builder_rs232phyrx_state)
		1'd1: begin
			main_basesoc_rx_enable <= 1'd1;
			if (main_basesoc_rx_tick) begin
				main_basesoc_rx_count_rs232phyrx_next_value0 <= (main_basesoc_rx_count + 1'd1);
				main_basesoc_rx_count_rs232phyrx_next_value_ce0 <= 1'd1;
				main_basesoc_rx_data_rs232phyrx_next_value1 <= {main_basesoc_rx_rx, main_basesoc_rx_data[7:1]};
				main_basesoc_rx_data_rs232phyrx_next_value_ce1 <= 1'd1;
				if ((main_basesoc_rx_count == 4'd9)) begin
					main_basesoc_rx_source_valid <= (main_basesoc_rx_rx == 1'd1);
					main_basesoc_rx_source_payload_data <= main_basesoc_rx_data;
					builder_rs232phyrx_next_state <= 1'd0;
				end
			end
		end
		default: begin
			main_basesoc_rx_count_rs232phyrx_next_value0 <= 1'd0;
			main_basesoc_rx_count_rs232phyrx_next_value_ce0 <= 1'd1;
			if (((main_basesoc_rx_rx == 1'd0) & (main_basesoc_rx_rx_d == 1'd1))) begin
				builder_rs232phyrx_next_state <= 1'd1;
			end
		end
	endcase
end
assign main_basesoc_uart_uart_sink_valid = main_basesoc_rx_source_valid;
assign main_basesoc_rx_source_ready = main_basesoc_uart_uart_sink_ready;
assign main_basesoc_uart_uart_sink_first = main_basesoc_rx_source_first;
assign main_basesoc_uart_uart_sink_last = main_basesoc_rx_source_last;
assign main_basesoc_uart_uart_sink_payload_data = main_basesoc_rx_source_payload_data;
assign main_basesoc_tx_sink_valid = main_basesoc_uart_uart_source_valid;
assign main_basesoc_uart_uart_source_ready = main_basesoc_tx_sink_ready;
assign main_basesoc_tx_sink_first = main_basesoc_uart_uart_source_first;
assign main_basesoc_tx_sink_last = main_basesoc_uart_uart_source_last;
assign main_basesoc_tx_sink_payload_data = main_basesoc_uart_uart_source_payload_data;
assign main_basesoc_uart_tx_fifo_sink_valid = main_basesoc_uart_rxtx_re;
assign main_basesoc_uart_tx_fifo_sink_payload_data = main_basesoc_uart_rxtx_r;
assign main_basesoc_uart_uart_source_valid = main_basesoc_uart_tx_fifo_source_valid;
assign main_basesoc_uart_tx_fifo_source_ready = main_basesoc_uart_uart_source_ready;
assign main_basesoc_uart_uart_source_first = main_basesoc_uart_tx_fifo_source_first;
assign main_basesoc_uart_uart_source_last = main_basesoc_uart_tx_fifo_source_last;
assign main_basesoc_uart_uart_source_payload_data = main_basesoc_uart_tx_fifo_source_payload_data;
assign main_basesoc_uart_txfull_status = (~main_basesoc_uart_tx_fifo_sink_ready);
assign main_basesoc_uart_txempty_status = (~main_basesoc_uart_tx_fifo_source_valid);
assign main_basesoc_uart_tx_trigger = main_basesoc_uart_tx_fifo_sink_ready;
assign main_basesoc_uart_rx_fifo_sink_valid = main_basesoc_uart_uart_sink_valid;
assign main_basesoc_uart_uart_sink_ready = main_basesoc_uart_rx_fifo_sink_ready;
assign main_basesoc_uart_rx_fifo_sink_first = main_basesoc_uart_uart_sink_first;
assign main_basesoc_uart_rx_fifo_sink_last = main_basesoc_uart_uart_sink_last;
assign main_basesoc_uart_rx_fifo_sink_payload_data = main_basesoc_uart_uart_sink_payload_data;
assign main_basesoc_uart_rxtx_w = main_basesoc_uart_rx_fifo_source_payload_data;
assign main_basesoc_uart_rx_fifo_source_ready = (main_basesoc_uart_rx_clear | (1'd0 & main_basesoc_uart_rxtx_we));
assign main_basesoc_uart_rxempty_status = (~main_basesoc_uart_rx_fifo_source_valid);
assign main_basesoc_uart_rxfull_status = (~main_basesoc_uart_rx_fifo_sink_ready);
assign main_basesoc_uart_rx_trigger = main_basesoc_uart_rx_fifo_source_valid;
assign main_basesoc_uart_tx0 = main_basesoc_uart_tx_status;
assign main_basesoc_uart_tx1 = main_basesoc_uart_tx_pending;
always @(*) begin
	main_basesoc_uart_tx_clear <= 1'd0;
	if ((main_basesoc_uart_pending_re & main_basesoc_uart_pending_r[0])) begin
		main_basesoc_uart_tx_clear <= 1'd1;
	end
end
assign main_basesoc_uart_rx0 = main_basesoc_uart_rx_status;
assign main_basesoc_uart_rx1 = main_basesoc_uart_rx_pending;
always @(*) begin
	main_basesoc_uart_rx_clear <= 1'd0;
	if ((main_basesoc_uart_pending_re & main_basesoc_uart_pending_r[1])) begin
		main_basesoc_uart_rx_clear <= 1'd1;
	end
end
assign main_basesoc_uart_irq = ((main_basesoc_uart_pending_status[0] & main_basesoc_uart_enable_storage[0]) | (main_basesoc_uart_pending_status[1] & main_basesoc_uart_enable_storage[1]));
assign main_basesoc_uart_tx_status = main_basesoc_uart_tx_trigger;
assign main_basesoc_uart_rx_status = main_basesoc_uart_rx_trigger;
assign main_basesoc_uart_tx_fifo_syncfifo_din = {main_basesoc_uart_tx_fifo_fifo_in_last, main_basesoc_uart_tx_fifo_fifo_in_first, main_basesoc_uart_tx_fifo_fifo_in_payload_data};
assign {main_basesoc_uart_tx_fifo_fifo_out_last, main_basesoc_uart_tx_fifo_fifo_out_first, main_basesoc_uart_tx_fifo_fifo_out_payload_data} = main_basesoc_uart_tx_fifo_syncfifo_dout;
assign main_basesoc_uart_tx_fifo_sink_ready = main_basesoc_uart_tx_fifo_syncfifo_writable;
assign main_basesoc_uart_tx_fifo_syncfifo_we = main_basesoc_uart_tx_fifo_sink_valid;
assign main_basesoc_uart_tx_fifo_fifo_in_first = main_basesoc_uart_tx_fifo_sink_first;
assign main_basesoc_uart_tx_fifo_fifo_in_last = main_basesoc_uart_tx_fifo_sink_last;
assign main_basesoc_uart_tx_fifo_fifo_in_payload_data = main_basesoc_uart_tx_fifo_sink_payload_data;
assign main_basesoc_uart_tx_fifo_source_valid = main_basesoc_uart_tx_fifo_readable;
assign main_basesoc_uart_tx_fifo_source_first = main_basesoc_uart_tx_fifo_fifo_out_first;
assign main_basesoc_uart_tx_fifo_source_last = main_basesoc_uart_tx_fifo_fifo_out_last;
assign main_basesoc_uart_tx_fifo_source_payload_data = main_basesoc_uart_tx_fifo_fifo_out_payload_data;
assign main_basesoc_uart_tx_fifo_re = main_basesoc_uart_tx_fifo_source_ready;
assign main_basesoc_uart_tx_fifo_syncfifo_re = (main_basesoc_uart_tx_fifo_syncfifo_readable & ((~main_basesoc_uart_tx_fifo_readable) | main_basesoc_uart_tx_fifo_re));
assign main_basesoc_uart_tx_fifo_level1 = (main_basesoc_uart_tx_fifo_level0 + main_basesoc_uart_tx_fifo_readable);
always @(*) begin
	main_basesoc_uart_tx_fifo_wrport_adr <= 4'd0;
	if (main_basesoc_uart_tx_fifo_replace) begin
		main_basesoc_uart_tx_fifo_wrport_adr <= (main_basesoc_uart_tx_fifo_produce - 1'd1);
	end else begin
		main_basesoc_uart_tx_fifo_wrport_adr <= main_basesoc_uart_tx_fifo_produce;
	end
end
assign main_basesoc_uart_tx_fifo_wrport_dat_w = main_basesoc_uart_tx_fifo_syncfifo_din;
assign main_basesoc_uart_tx_fifo_wrport_we = (main_basesoc_uart_tx_fifo_syncfifo_we & (main_basesoc_uart_tx_fifo_syncfifo_writable | main_basesoc_uart_tx_fifo_replace));
assign main_basesoc_uart_tx_fifo_do_read = (main_basesoc_uart_tx_fifo_syncfifo_readable & main_basesoc_uart_tx_fifo_syncfifo_re);
assign main_basesoc_uart_tx_fifo_rdport_adr = main_basesoc_uart_tx_fifo_consume;
assign main_basesoc_uart_tx_fifo_syncfifo_dout = main_basesoc_uart_tx_fifo_rdport_dat_r;
assign main_basesoc_uart_tx_fifo_rdport_re = main_basesoc_uart_tx_fifo_do_read;
assign main_basesoc_uart_tx_fifo_syncfifo_writable = (main_basesoc_uart_tx_fifo_level0 != 5'd16);
assign main_basesoc_uart_tx_fifo_syncfifo_readable = (main_basesoc_uart_tx_fifo_level0 != 1'd0);
assign main_basesoc_uart_rx_fifo_syncfifo_din = {main_basesoc_uart_rx_fifo_fifo_in_last, main_basesoc_uart_rx_fifo_fifo_in_first, main_basesoc_uart_rx_fifo_fifo_in_payload_data};
assign {main_basesoc_uart_rx_fifo_fifo_out_last, main_basesoc_uart_rx_fifo_fifo_out_first, main_basesoc_uart_rx_fifo_fifo_out_payload_data} = main_basesoc_uart_rx_fifo_syncfifo_dout;
assign main_basesoc_uart_rx_fifo_sink_ready = main_basesoc_uart_rx_fifo_syncfifo_writable;
assign main_basesoc_uart_rx_fifo_syncfifo_we = main_basesoc_uart_rx_fifo_sink_valid;
assign main_basesoc_uart_rx_fifo_fifo_in_first = main_basesoc_uart_rx_fifo_sink_first;
assign main_basesoc_uart_rx_fifo_fifo_in_last = main_basesoc_uart_rx_fifo_sink_last;
assign main_basesoc_uart_rx_fifo_fifo_in_payload_data = main_basesoc_uart_rx_fifo_sink_payload_data;
assign main_basesoc_uart_rx_fifo_source_valid = main_basesoc_uart_rx_fifo_readable;
assign main_basesoc_uart_rx_fifo_source_first = main_basesoc_uart_rx_fifo_fifo_out_first;
assign main_basesoc_uart_rx_fifo_source_last = main_basesoc_uart_rx_fifo_fifo_out_last;
assign main_basesoc_uart_rx_fifo_source_payload_data = main_basesoc_uart_rx_fifo_fifo_out_payload_data;
assign main_basesoc_uart_rx_fifo_re = main_basesoc_uart_rx_fifo_source_ready;
assign main_basesoc_uart_rx_fifo_syncfifo_re = (main_basesoc_uart_rx_fifo_syncfifo_readable & ((~main_basesoc_uart_rx_fifo_readable) | main_basesoc_uart_rx_fifo_re));
assign main_basesoc_uart_rx_fifo_level1 = (main_basesoc_uart_rx_fifo_level0 + main_basesoc_uart_rx_fifo_readable);
always @(*) begin
	main_basesoc_uart_rx_fifo_wrport_adr <= 4'd0;
	if (main_basesoc_uart_rx_fifo_replace) begin
		main_basesoc_uart_rx_fifo_wrport_adr <= (main_basesoc_uart_rx_fifo_produce - 1'd1);
	end else begin
		main_basesoc_uart_rx_fifo_wrport_adr <= main_basesoc_uart_rx_fifo_produce;
	end
end
assign main_basesoc_uart_rx_fifo_wrport_dat_w = main_basesoc_uart_rx_fifo_syncfifo_din;
assign main_basesoc_uart_rx_fifo_wrport_we = (main_basesoc_uart_rx_fifo_syncfifo_we & (main_basesoc_uart_rx_fifo_syncfifo_writable | main_basesoc_uart_rx_fifo_replace));
assign main_basesoc_uart_rx_fifo_do_read = (main_basesoc_uart_rx_fifo_syncfifo_readable & main_basesoc_uart_rx_fifo_syncfifo_re);
assign main_basesoc_uart_rx_fifo_rdport_adr = main_basesoc_uart_rx_fifo_consume;
assign main_basesoc_uart_rx_fifo_syncfifo_dout = main_basesoc_uart_rx_fifo_rdport_dat_r;
assign main_basesoc_uart_rx_fifo_rdport_re = main_basesoc_uart_rx_fifo_do_read;
assign main_basesoc_uart_rx_fifo_syncfifo_writable = (main_basesoc_uart_rx_fifo_level0 != 5'd16);
assign main_basesoc_uart_rx_fifo_syncfifo_readable = (main_basesoc_uart_rx_fifo_level0 != 1'd0);
assign main_basesoc_timer_zero_trigger = (main_basesoc_timer_value == 1'd0);
assign main_basesoc_timer_zero0 = main_basesoc_timer_zero_status;
assign main_basesoc_timer_zero1 = main_basesoc_timer_zero_pending;
always @(*) begin
	main_basesoc_timer_zero_clear <= 1'd0;
	if ((main_basesoc_timer_pending_re & main_basesoc_timer_pending_r)) begin
		main_basesoc_timer_zero_clear <= 1'd1;
	end
end
assign main_basesoc_timer_irq = (main_basesoc_timer_pending_status & main_basesoc_timer_enable_storage);
assign main_basesoc_timer_zero_status = main_basesoc_timer_zero_trigger;
assign main_crg_por_done = (main_crg_por_count == 1'd0);
assign por_clk = main_crg_clkout;
assign main_crg_clkin = por_clk;
assign main_datain0 = main_bus_dat_w[31:0];
assign main_datain1 = main_bus_dat_w[31:0];
always @(*) begin
	main_wren1 <= 1'd0;
	main_cs0 <= 1'd0;
	main_wren0 <= 1'd0;
	main_cs1 <= 1'd0;
	main_bus_dat_r <= 32'd0;
	if ((main_bus_adr[15:14] == 1'd0)) begin
		main_cs0 <= 1'd1;
		main_wren0 <= ((main_bus_we & main_bus_stb) & main_bus_cyc);
		main_bus_dat_r[31:0] <= main_dataout0;
	end
	if ((main_bus_adr[15:14] == 1'd1)) begin
		main_cs1 <= 1'd1;
		main_wren1 <= ((main_bus_we & main_bus_stb) & main_bus_cyc);
		main_bus_dat_r[31:0] <= main_dataout1;
	end
end
assign main_wait = (~main_done);
always @(*) begin
	user_led0 <= 1'd0;
	user_led1 <= 1'd0;
	user_led2 <= 1'd0;
	user_led3 <= 1'd0;
	user_led4 <= 1'd0;
	user_led5 <= 1'd0;
	user_led6 <= 1'd0;
	user_led7 <= 1'd0;
	user_led8 <= 1'd0;
	user_led9 <= 1'd0;
	user_led10 <= 1'd0;
	user_led11 <= 1'd0;
	user_led12 <= 1'd0;
	user_led13 <= 1'd0;
	if ((main_mode == 1'd1)) begin
		{user_led13, user_led12, user_led11, user_led10, user_led9, user_led8, user_led7, user_led6, user_led5, user_led4, user_led3, user_led2, user_led1, user_led0} <= main_storage;
	end else begin
		{user_led13, user_led12, user_led11, user_led10, user_led9, user_led8, user_led7, user_led6, user_led5, user_led4, user_led3, user_led2, user_led1, user_led0} <= main_chaser;
	end
end
assign main_done = (main_count == 1'd0);
always @(*) begin
	builder_basesoc_adr <= 14'd0;
	builder_basesoc_we <= 1'd0;
	builder_basesoc_dat_w <= 32'd0;
	builder_basesoc_wishbone_ack <= 1'd0;
	builder_next_state <= 1'd0;
	builder_basesoc_wishbone_dat_r <= 32'd0;
	builder_next_state <= builder_state;
	case (builder_state)
		1'd1: begin
			builder_basesoc_wishbone_ack <= 1'd1;
			builder_basesoc_wishbone_dat_r <= builder_basesoc_dat_r;
			builder_next_state <= 1'd0;
		end
		default: begin
			builder_basesoc_dat_w <= builder_basesoc_wishbone_dat_w;
			if ((builder_basesoc_wishbone_cyc & builder_basesoc_wishbone_stb)) begin
				builder_basesoc_adr <= builder_basesoc_wishbone_adr;
				builder_basesoc_we <= (builder_basesoc_wishbone_we & (builder_basesoc_wishbone_sel != 1'd0));
				builder_next_state <= 1'd1;
			end
		end
	endcase
end
assign builder_shared_adr = builder_array_muxed0;
assign builder_shared_dat_w = builder_array_muxed1;
assign builder_shared_sel = builder_array_muxed2;
assign builder_shared_cyc = builder_array_muxed3;
assign builder_shared_stb = builder_array_muxed4;
assign builder_shared_we = builder_array_muxed5;
assign builder_shared_cti = builder_array_muxed6;
assign builder_shared_bte = builder_array_muxed7;
assign main_basesoc_ibus_dat_r = builder_shared_dat_r;
assign main_basesoc_dbus_dat_r = builder_shared_dat_r;
assign main_basesoc_ibus_ack = (builder_shared_ack & (builder_grant == 1'd0));
assign main_basesoc_dbus_ack = (builder_shared_ack & (builder_grant == 1'd1));
assign main_basesoc_ibus_err = (builder_shared_err & (builder_grant == 1'd0));
assign main_basesoc_dbus_err = (builder_shared_err & (builder_grant == 1'd1));
assign builder_request = {main_basesoc_dbus_cyc, main_basesoc_ibus_cyc};
always @(*) begin
	builder_slave_sel <= 3'd0;
	builder_slave_sel[0] <= (builder_shared_adr[29:15] == 1'd0);
	builder_slave_sel[1] <= (builder_shared_adr[29:15] == 12'd2048);
	builder_slave_sel[2] <= (builder_shared_adr[29:14] == 16'd61440);
end
assign main_basesoc_ram_bus_adr = builder_shared_adr;
assign main_basesoc_ram_bus_dat_w = builder_shared_dat_w;
assign main_basesoc_ram_bus_sel = builder_shared_sel;
assign main_basesoc_ram_bus_stb = builder_shared_stb;
assign main_basesoc_ram_bus_we = builder_shared_we;
assign main_basesoc_ram_bus_cti = builder_shared_cti;
assign main_basesoc_ram_bus_bte = builder_shared_bte;
assign main_bus_adr = builder_shared_adr;
assign main_bus_dat_w = builder_shared_dat_w;
assign main_bus_sel = builder_shared_sel;
assign main_bus_stb = builder_shared_stb;
assign main_bus_we = builder_shared_we;
assign main_bus_cti = builder_shared_cti;
assign main_bus_bte = builder_shared_bte;
assign builder_basesoc_wishbone_adr = builder_shared_adr;
assign builder_basesoc_wishbone_dat_w = builder_shared_dat_w;
assign builder_basesoc_wishbone_sel = builder_shared_sel;
assign builder_basesoc_wishbone_stb = builder_shared_stb;
assign builder_basesoc_wishbone_we = builder_shared_we;
assign builder_basesoc_wishbone_cti = builder_shared_cti;
assign builder_basesoc_wishbone_bte = builder_shared_bte;
assign main_basesoc_ram_bus_cyc = (builder_shared_cyc & builder_slave_sel[0]);
assign main_bus_cyc = (builder_shared_cyc & builder_slave_sel[1]);
assign builder_basesoc_wishbone_cyc = (builder_shared_cyc & builder_slave_sel[2]);
assign builder_shared_err = ((main_basesoc_ram_bus_err | main_bus_err) | builder_basesoc_wishbone_err);
assign builder_wait = ((builder_shared_stb & builder_shared_cyc) & (~builder_shared_ack));
always @(*) begin
	builder_shared_dat_r <= 32'd0;
	builder_error <= 1'd0;
	builder_shared_ack <= 1'd0;
	builder_shared_ack <= ((main_basesoc_ram_bus_ack | main_bus_ack) | builder_basesoc_wishbone_ack);
	builder_shared_dat_r <= ((({32{builder_slave_sel_r[0]}} & main_basesoc_ram_bus_dat_r) | ({32{builder_slave_sel_r[1]}} & main_bus_dat_r)) | ({32{builder_slave_sel_r[2]}} & builder_basesoc_wishbone_dat_r));
	if (builder_done) begin
		builder_shared_dat_r <= 32'd4294967295;
		builder_shared_ack <= 1'd1;
		builder_error <= 1'd1;
	end
end
assign builder_done = (builder_count == 1'd0);
assign builder_csr_bankarray_csrbank0_sel = (builder_csr_bankarray_interface0_bank_bus_adr[13:9] == 1'd0);
assign builder_csr_bankarray_csrbank0_reset0_r = builder_csr_bankarray_interface0_bank_bus_dat_w[1:0];
always @(*) begin
	builder_csr_bankarray_csrbank0_reset0_we <= 1'd0;
	builder_csr_bankarray_csrbank0_reset0_re <= 1'd0;
	if ((builder_csr_bankarray_csrbank0_sel & (builder_csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd0))) begin
		builder_csr_bankarray_csrbank0_reset0_re <= builder_csr_bankarray_interface0_bank_bus_we;
		builder_csr_bankarray_csrbank0_reset0_we <= (~builder_csr_bankarray_interface0_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank0_scratch0_r = builder_csr_bankarray_interface0_bank_bus_dat_w[31:0];
always @(*) begin
	builder_csr_bankarray_csrbank0_scratch0_re <= 1'd0;
	builder_csr_bankarray_csrbank0_scratch0_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank0_sel & (builder_csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd1))) begin
		builder_csr_bankarray_csrbank0_scratch0_re <= builder_csr_bankarray_interface0_bank_bus_we;
		builder_csr_bankarray_csrbank0_scratch0_we <= (~builder_csr_bankarray_interface0_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank0_bus_errors_r = builder_csr_bankarray_interface0_bank_bus_dat_w[31:0];
always @(*) begin
	builder_csr_bankarray_csrbank0_bus_errors_we <= 1'd0;
	builder_csr_bankarray_csrbank0_bus_errors_re <= 1'd0;
	if ((builder_csr_bankarray_csrbank0_sel & (builder_csr_bankarray_interface0_bank_bus_adr[8:0] == 2'd2))) begin
		builder_csr_bankarray_csrbank0_bus_errors_re <= builder_csr_bankarray_interface0_bank_bus_we;
		builder_csr_bankarray_csrbank0_bus_errors_we <= (~builder_csr_bankarray_interface0_bank_bus_we);
	end
end
always @(*) begin
	main_basesoc_soc_rst <= 1'd0;
	if (main_basesoc_reset_re) begin
		main_basesoc_soc_rst <= main_basesoc_reset_storage[0];
	end
end
assign main_basesoc_cpu_rst = main_basesoc_reset_storage[1];
assign builder_csr_bankarray_csrbank0_reset0_w = main_basesoc_reset_storage[1:0];
assign builder_csr_bankarray_csrbank0_scratch0_w = main_basesoc_scratch_storage[31:0];
assign builder_csr_bankarray_csrbank0_bus_errors_w = main_basesoc_bus_errors_status[31:0];
assign main_basesoc_bus_errors_we = builder_csr_bankarray_csrbank0_bus_errors_we;
assign builder_csr_bankarray_sel = (builder_csr_bankarray_sram_bus_adr[13:9] == 1'd1);
always @(*) begin
	builder_csr_bankarray_sram_bus_dat_r <= 32'd0;
	if (builder_csr_bankarray_sel_r) begin
		builder_csr_bankarray_sram_bus_dat_r <= builder_csr_bankarray_dat_r;
	end
end
assign builder_csr_bankarray_adr = builder_csr_bankarray_sram_bus_adr[5:0];
assign builder_csr_bankarray_csrbank1_sel = (builder_csr_bankarray_interface1_bank_bus_adr[13:9] == 2'd2);
assign builder_csr_bankarray_csrbank1_out0_r = builder_csr_bankarray_interface1_bank_bus_dat_w[13:0];
always @(*) begin
	builder_csr_bankarray_csrbank1_out0_re <= 1'd0;
	builder_csr_bankarray_csrbank1_out0_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank1_sel & (builder_csr_bankarray_interface1_bank_bus_adr[8:0] == 1'd0))) begin
		builder_csr_bankarray_csrbank1_out0_re <= builder_csr_bankarray_interface1_bank_bus_we;
		builder_csr_bankarray_csrbank1_out0_we <= (~builder_csr_bankarray_interface1_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank1_out0_w = main_storage[13:0];
assign builder_csr_bankarray_csrbank2_sel = (builder_csr_bankarray_interface2_bank_bus_adr[13:9] == 2'd3);
assign builder_csr_bankarray_csrbank2_load0_r = builder_csr_bankarray_interface2_bank_bus_dat_w[31:0];
always @(*) begin
	builder_csr_bankarray_csrbank2_load0_re <= 1'd0;
	builder_csr_bankarray_csrbank2_load0_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 1'd0))) begin
		builder_csr_bankarray_csrbank2_load0_re <= builder_csr_bankarray_interface2_bank_bus_we;
		builder_csr_bankarray_csrbank2_load0_we <= (~builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank2_reload0_r = builder_csr_bankarray_interface2_bank_bus_dat_w[31:0];
always @(*) begin
	builder_csr_bankarray_csrbank2_reload0_we <= 1'd0;
	builder_csr_bankarray_csrbank2_reload0_re <= 1'd0;
	if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 1'd1))) begin
		builder_csr_bankarray_csrbank2_reload0_re <= builder_csr_bankarray_interface2_bank_bus_we;
		builder_csr_bankarray_csrbank2_reload0_we <= (~builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank2_en0_r = builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
	builder_csr_bankarray_csrbank2_en0_re <= 1'd0;
	builder_csr_bankarray_csrbank2_en0_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 2'd2))) begin
		builder_csr_bankarray_csrbank2_en0_re <= builder_csr_bankarray_interface2_bank_bus_we;
		builder_csr_bankarray_csrbank2_en0_we <= (~builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank2_update_value0_r = builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
	builder_csr_bankarray_csrbank2_update_value0_re <= 1'd0;
	builder_csr_bankarray_csrbank2_update_value0_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 2'd3))) begin
		builder_csr_bankarray_csrbank2_update_value0_re <= builder_csr_bankarray_interface2_bank_bus_we;
		builder_csr_bankarray_csrbank2_update_value0_we <= (~builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank2_value_r = builder_csr_bankarray_interface2_bank_bus_dat_w[31:0];
always @(*) begin
	builder_csr_bankarray_csrbank2_value_we <= 1'd0;
	builder_csr_bankarray_csrbank2_value_re <= 1'd0;
	if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd4))) begin
		builder_csr_bankarray_csrbank2_value_re <= builder_csr_bankarray_interface2_bank_bus_we;
		builder_csr_bankarray_csrbank2_value_we <= (~builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank2_ev_status_r = builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
	builder_csr_bankarray_csrbank2_ev_status_re <= 1'd0;
	builder_csr_bankarray_csrbank2_ev_status_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd5))) begin
		builder_csr_bankarray_csrbank2_ev_status_re <= builder_csr_bankarray_interface2_bank_bus_we;
		builder_csr_bankarray_csrbank2_ev_status_we <= (~builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank2_ev_pending_r = builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
	builder_csr_bankarray_csrbank2_ev_pending_re <= 1'd0;
	builder_csr_bankarray_csrbank2_ev_pending_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd6))) begin
		builder_csr_bankarray_csrbank2_ev_pending_re <= builder_csr_bankarray_interface2_bank_bus_we;
		builder_csr_bankarray_csrbank2_ev_pending_we <= (~builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank2_ev_enable0_r = builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
	builder_csr_bankarray_csrbank2_ev_enable0_we <= 1'd0;
	builder_csr_bankarray_csrbank2_ev_enable0_re <= 1'd0;
	if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd7))) begin
		builder_csr_bankarray_csrbank2_ev_enable0_re <= builder_csr_bankarray_interface2_bank_bus_we;
		builder_csr_bankarray_csrbank2_ev_enable0_we <= (~builder_csr_bankarray_interface2_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank2_load0_w = main_basesoc_timer_load_storage[31:0];
assign builder_csr_bankarray_csrbank2_reload0_w = main_basesoc_timer_reload_storage[31:0];
assign builder_csr_bankarray_csrbank2_en0_w = main_basesoc_timer_en_storage;
assign builder_csr_bankarray_csrbank2_update_value0_w = main_basesoc_timer_update_value_storage;
assign builder_csr_bankarray_csrbank2_value_w = main_basesoc_timer_value_status[31:0];
assign main_basesoc_timer_value_we = builder_csr_bankarray_csrbank2_value_we;
assign main_basesoc_timer_status_status = main_basesoc_timer_zero0;
assign builder_csr_bankarray_csrbank2_ev_status_w = main_basesoc_timer_status_status;
assign main_basesoc_timer_status_we = builder_csr_bankarray_csrbank2_ev_status_we;
assign main_basesoc_timer_pending_status = main_basesoc_timer_zero1;
assign builder_csr_bankarray_csrbank2_ev_pending_w = main_basesoc_timer_pending_status;
assign main_basesoc_timer_pending_we = builder_csr_bankarray_csrbank2_ev_pending_we;
assign main_basesoc_timer_zero2 = main_basesoc_timer_enable_storage;
assign builder_csr_bankarray_csrbank2_ev_enable0_w = main_basesoc_timer_enable_storage;
assign builder_csr_bankarray_csrbank3_sel = (builder_csr_bankarray_interface3_bank_bus_adr[13:9] == 3'd4);
assign main_basesoc_uart_rxtx_r = builder_csr_bankarray_interface3_bank_bus_dat_w[7:0];
always @(*) begin
	main_basesoc_uart_rxtx_re <= 1'd0;
	main_basesoc_uart_rxtx_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 1'd0))) begin
		main_basesoc_uart_rxtx_re <= builder_csr_bankarray_interface3_bank_bus_we;
		main_basesoc_uart_rxtx_we <= (~builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank3_txfull_r = builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
	builder_csr_bankarray_csrbank3_txfull_we <= 1'd0;
	builder_csr_bankarray_csrbank3_txfull_re <= 1'd0;
	if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 1'd1))) begin
		builder_csr_bankarray_csrbank3_txfull_re <= builder_csr_bankarray_interface3_bank_bus_we;
		builder_csr_bankarray_csrbank3_txfull_we <= (~builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank3_rxempty_r = builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
	builder_csr_bankarray_csrbank3_rxempty_re <= 1'd0;
	builder_csr_bankarray_csrbank3_rxempty_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 2'd2))) begin
		builder_csr_bankarray_csrbank3_rxempty_re <= builder_csr_bankarray_interface3_bank_bus_we;
		builder_csr_bankarray_csrbank3_rxempty_we <= (~builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank3_ev_status_r = builder_csr_bankarray_interface3_bank_bus_dat_w[1:0];
always @(*) begin
	builder_csr_bankarray_csrbank3_ev_status_re <= 1'd0;
	builder_csr_bankarray_csrbank3_ev_status_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 2'd3))) begin
		builder_csr_bankarray_csrbank3_ev_status_re <= builder_csr_bankarray_interface3_bank_bus_we;
		builder_csr_bankarray_csrbank3_ev_status_we <= (~builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank3_ev_pending_r = builder_csr_bankarray_interface3_bank_bus_dat_w[1:0];
always @(*) begin
	builder_csr_bankarray_csrbank3_ev_pending_we <= 1'd0;
	builder_csr_bankarray_csrbank3_ev_pending_re <= 1'd0;
	if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd4))) begin
		builder_csr_bankarray_csrbank3_ev_pending_re <= builder_csr_bankarray_interface3_bank_bus_we;
		builder_csr_bankarray_csrbank3_ev_pending_we <= (~builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank3_ev_enable0_r = builder_csr_bankarray_interface3_bank_bus_dat_w[1:0];
always @(*) begin
	builder_csr_bankarray_csrbank3_ev_enable0_re <= 1'd0;
	builder_csr_bankarray_csrbank3_ev_enable0_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd5))) begin
		builder_csr_bankarray_csrbank3_ev_enable0_re <= builder_csr_bankarray_interface3_bank_bus_we;
		builder_csr_bankarray_csrbank3_ev_enable0_we <= (~builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank3_txempty_r = builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
	builder_csr_bankarray_csrbank3_txempty_re <= 1'd0;
	builder_csr_bankarray_csrbank3_txempty_we <= 1'd0;
	if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd6))) begin
		builder_csr_bankarray_csrbank3_txempty_re <= builder_csr_bankarray_interface3_bank_bus_we;
		builder_csr_bankarray_csrbank3_txempty_we <= (~builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank3_rxfull_r = builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
	builder_csr_bankarray_csrbank3_rxfull_we <= 1'd0;
	builder_csr_bankarray_csrbank3_rxfull_re <= 1'd0;
	if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd7))) begin
		builder_csr_bankarray_csrbank3_rxfull_re <= builder_csr_bankarray_interface3_bank_bus_we;
		builder_csr_bankarray_csrbank3_rxfull_we <= (~builder_csr_bankarray_interface3_bank_bus_we);
	end
end
assign builder_csr_bankarray_csrbank3_txfull_w = main_basesoc_uart_txfull_status;
assign main_basesoc_uart_txfull_we = builder_csr_bankarray_csrbank3_txfull_we;
assign builder_csr_bankarray_csrbank3_rxempty_w = main_basesoc_uart_rxempty_status;
assign main_basesoc_uart_rxempty_we = builder_csr_bankarray_csrbank3_rxempty_we;
always @(*) begin
	main_basesoc_uart_status_status <= 2'd0;
	main_basesoc_uart_status_status[0] <= main_basesoc_uart_tx0;
	main_basesoc_uart_status_status[1] <= main_basesoc_uart_rx0;
end
assign builder_csr_bankarray_csrbank3_ev_status_w = main_basesoc_uart_status_status[1:0];
assign main_basesoc_uart_status_we = builder_csr_bankarray_csrbank3_ev_status_we;
always @(*) begin
	main_basesoc_uart_pending_status <= 2'd0;
	main_basesoc_uart_pending_status[0] <= main_basesoc_uart_tx1;
	main_basesoc_uart_pending_status[1] <= main_basesoc_uart_rx1;
end
assign builder_csr_bankarray_csrbank3_ev_pending_w = main_basesoc_uart_pending_status[1:0];
assign main_basesoc_uart_pending_we = builder_csr_bankarray_csrbank3_ev_pending_we;
assign main_basesoc_uart_tx2 = main_basesoc_uart_enable_storage[0];
assign main_basesoc_uart_rx2 = main_basesoc_uart_enable_storage[1];
assign builder_csr_bankarray_csrbank3_ev_enable0_w = main_basesoc_uart_enable_storage[1:0];
assign builder_csr_bankarray_csrbank3_txempty_w = main_basesoc_uart_txempty_status;
assign main_basesoc_uart_txempty_we = builder_csr_bankarray_csrbank3_txempty_we;
assign builder_csr_bankarray_csrbank3_rxfull_w = main_basesoc_uart_rxfull_status;
assign main_basesoc_uart_rxfull_we = builder_csr_bankarray_csrbank3_rxfull_we;
assign builder_csr_interconnect_adr = builder_basesoc_adr;
assign builder_csr_interconnect_we = builder_basesoc_we;
assign builder_csr_interconnect_dat_w = builder_basesoc_dat_w;
assign builder_basesoc_dat_r = builder_csr_interconnect_dat_r;
assign builder_csr_bankarray_interface0_bank_bus_adr = builder_csr_interconnect_adr;
assign builder_csr_bankarray_interface1_bank_bus_adr = builder_csr_interconnect_adr;
assign builder_csr_bankarray_interface2_bank_bus_adr = builder_csr_interconnect_adr;
assign builder_csr_bankarray_interface3_bank_bus_adr = builder_csr_interconnect_adr;
assign builder_csr_bankarray_sram_bus_adr = builder_csr_interconnect_adr;
assign builder_csr_bankarray_interface0_bank_bus_we = builder_csr_interconnect_we;
assign builder_csr_bankarray_interface1_bank_bus_we = builder_csr_interconnect_we;
assign builder_csr_bankarray_interface2_bank_bus_we = builder_csr_interconnect_we;
assign builder_csr_bankarray_interface3_bank_bus_we = builder_csr_interconnect_we;
assign builder_csr_bankarray_sram_bus_we = builder_csr_interconnect_we;
assign builder_csr_bankarray_interface0_bank_bus_dat_w = builder_csr_interconnect_dat_w;
assign builder_csr_bankarray_interface1_bank_bus_dat_w = builder_csr_interconnect_dat_w;
assign builder_csr_bankarray_interface2_bank_bus_dat_w = builder_csr_interconnect_dat_w;
assign builder_csr_bankarray_interface3_bank_bus_dat_w = builder_csr_interconnect_dat_w;
assign builder_csr_bankarray_sram_bus_dat_w = builder_csr_interconnect_dat_w;
assign builder_csr_interconnect_dat_r = ((((builder_csr_bankarray_interface0_bank_bus_dat_r | builder_csr_bankarray_interface1_bank_bus_dat_r) | builder_csr_bankarray_interface2_bank_bus_dat_r) | builder_csr_bankarray_interface3_bank_bus_dat_r) | builder_csr_bankarray_sram_bus_dat_r);
always @(*) begin
	builder_array_muxed0 <= 30'd0;
	case (builder_grant)
		1'd0: begin
			builder_array_muxed0 <= main_basesoc_ibus_adr;
		end
		default: begin
			builder_array_muxed0 <= main_basesoc_dbus_adr;
		end
	endcase
end
always @(*) begin
	builder_array_muxed1 <= 32'd0;
	case (builder_grant)
		1'd0: begin
			builder_array_muxed1 <= main_basesoc_ibus_dat_w;
		end
		default: begin
			builder_array_muxed1 <= main_basesoc_dbus_dat_w;
		end
	endcase
end
always @(*) begin
	builder_array_muxed2 <= 4'd0;
	case (builder_grant)
		1'd0: begin
			builder_array_muxed2 <= main_basesoc_ibus_sel;
		end
		default: begin
			builder_array_muxed2 <= main_basesoc_dbus_sel;
		end
	endcase
end
always @(*) begin
	builder_array_muxed3 <= 1'd0;
	case (builder_grant)
		1'd0: begin
			builder_array_muxed3 <= main_basesoc_ibus_cyc;
		end
		default: begin
			builder_array_muxed3 <= main_basesoc_dbus_cyc;
		end
	endcase
end
always @(*) begin
	builder_array_muxed4 <= 1'd0;
	case (builder_grant)
		1'd0: begin
			builder_array_muxed4 <= main_basesoc_ibus_stb;
		end
		default: begin
			builder_array_muxed4 <= main_basesoc_dbus_stb;
		end
	endcase
end
always @(*) begin
	builder_array_muxed5 <= 1'd0;
	case (builder_grant)
		1'd0: begin
			builder_array_muxed5 <= main_basesoc_ibus_we;
		end
		default: begin
			builder_array_muxed5 <= main_basesoc_dbus_we;
		end
	endcase
end
always @(*) begin
	builder_array_muxed6 <= 3'd0;
	case (builder_grant)
		1'd0: begin
			builder_array_muxed6 <= main_basesoc_ibus_cti;
		end
		default: begin
			builder_array_muxed6 <= main_basesoc_dbus_cti;
		end
	endcase
end
always @(*) begin
	builder_array_muxed7 <= 2'd0;
	case (builder_grant)
		1'd0: begin
			builder_array_muxed7 <= main_basesoc_ibus_bte;
		end
		default: begin
			builder_array_muxed7 <= main_basesoc_dbus_bte;
		end
	endcase
end
assign main_basesoc_rx_rx = builder_regs1;

always @(posedge por_clk) begin
	if ((~main_crg_por_done)) begin
		main_crg_por_count <= (main_crg_por_count - 1'd1);
	end
	if (por_rst) begin
		main_crg_por_count <= 16'd65535;
	end
end

always @(posedge sys_clk) begin
	if ((main_basesoc_bus_errors != 32'd4294967295)) begin
		if (main_basesoc_bus_error) begin
			main_basesoc_bus_errors <= (main_basesoc_bus_errors + 1'd1);
		end
	end
	main_basesoc_ram_bus_ack <= 1'd0;
	if (((main_basesoc_ram_bus_cyc & main_basesoc_ram_bus_stb) & (~main_basesoc_ram_bus_ack))) begin
		main_basesoc_ram_bus_ack <= 1'd1;
	end
	{main_basesoc_tx_tick, main_basesoc_tx_phase} <= 23'd6597069;
	if (main_basesoc_tx_enable) begin
		{main_basesoc_tx_tick, main_basesoc_tx_phase} <= (main_basesoc_tx_phase + 23'd6597069);
	end
	builder_rs232phytx_state <= builder_rs232phytx_next_state;
	if (main_basesoc_tx_count_rs232phytx_next_value_ce0) begin
		main_basesoc_tx_count <= main_basesoc_tx_count_rs232phytx_next_value0;
	end
	if (main_basesoc_serial_tx_rs232phytx_next_value_ce1) begin
		serial_tx <= main_basesoc_serial_tx_rs232phytx_next_value1;
	end
	if (main_basesoc_tx_data_rs232phytx_next_value_ce2) begin
		main_basesoc_tx_data <= main_basesoc_tx_data_rs232phytx_next_value2;
	end
	main_basesoc_rx_rx_d <= main_basesoc_rx_rx;
	{main_basesoc_rx_tick, main_basesoc_rx_phase} <= 32'd2147483648;
	if (main_basesoc_rx_enable) begin
		{main_basesoc_rx_tick, main_basesoc_rx_phase} <= (main_basesoc_rx_phase + 23'd6597069);
	end
	builder_rs232phyrx_state <= builder_rs232phyrx_next_state;
	if (main_basesoc_rx_count_rs232phyrx_next_value_ce0) begin
		main_basesoc_rx_count <= main_basesoc_rx_count_rs232phyrx_next_value0;
	end
	if (main_basesoc_rx_data_rs232phyrx_next_value_ce1) begin
		main_basesoc_rx_data <= main_basesoc_rx_data_rs232phyrx_next_value1;
	end
	if (main_basesoc_uart_tx_clear) begin
		main_basesoc_uart_tx_pending <= 1'd0;
	end
	main_basesoc_uart_tx_trigger_d <= main_basesoc_uart_tx_trigger;
	if ((main_basesoc_uart_tx_trigger & (~main_basesoc_uart_tx_trigger_d))) begin
		main_basesoc_uart_tx_pending <= 1'd1;
	end
	if (main_basesoc_uart_rx_clear) begin
		main_basesoc_uart_rx_pending <= 1'd0;
	end
	main_basesoc_uart_rx_trigger_d <= main_basesoc_uart_rx_trigger;
	if ((main_basesoc_uart_rx_trigger & (~main_basesoc_uart_rx_trigger_d))) begin
		main_basesoc_uart_rx_pending <= 1'd1;
	end
	if (main_basesoc_uart_tx_fifo_syncfifo_re) begin
		main_basesoc_uart_tx_fifo_readable <= 1'd1;
	end else begin
		if (main_basesoc_uart_tx_fifo_re) begin
			main_basesoc_uart_tx_fifo_readable <= 1'd0;
		end
	end
	if (((main_basesoc_uart_tx_fifo_syncfifo_we & main_basesoc_uart_tx_fifo_syncfifo_writable) & (~main_basesoc_uart_tx_fifo_replace))) begin
		main_basesoc_uart_tx_fifo_produce <= (main_basesoc_uart_tx_fifo_produce + 1'd1);
	end
	if (main_basesoc_uart_tx_fifo_do_read) begin
		main_basesoc_uart_tx_fifo_consume <= (main_basesoc_uart_tx_fifo_consume + 1'd1);
	end
	if (((main_basesoc_uart_tx_fifo_syncfifo_we & main_basesoc_uart_tx_fifo_syncfifo_writable) & (~main_basesoc_uart_tx_fifo_replace))) begin
		if ((~main_basesoc_uart_tx_fifo_do_read)) begin
			main_basesoc_uart_tx_fifo_level0 <= (main_basesoc_uart_tx_fifo_level0 + 1'd1);
		end
	end else begin
		if (main_basesoc_uart_tx_fifo_do_read) begin
			main_basesoc_uart_tx_fifo_level0 <= (main_basesoc_uart_tx_fifo_level0 - 1'd1);
		end
	end
	if (main_basesoc_uart_rx_fifo_syncfifo_re) begin
		main_basesoc_uart_rx_fifo_readable <= 1'd1;
	end else begin
		if (main_basesoc_uart_rx_fifo_re) begin
			main_basesoc_uart_rx_fifo_readable <= 1'd0;
		end
	end
	if (((main_basesoc_uart_rx_fifo_syncfifo_we & main_basesoc_uart_rx_fifo_syncfifo_writable) & (~main_basesoc_uart_rx_fifo_replace))) begin
		main_basesoc_uart_rx_fifo_produce <= (main_basesoc_uart_rx_fifo_produce + 1'd1);
	end
	if (main_basesoc_uart_rx_fifo_do_read) begin
		main_basesoc_uart_rx_fifo_consume <= (main_basesoc_uart_rx_fifo_consume + 1'd1);
	end
	if (((main_basesoc_uart_rx_fifo_syncfifo_we & main_basesoc_uart_rx_fifo_syncfifo_writable) & (~main_basesoc_uart_rx_fifo_replace))) begin
		if ((~main_basesoc_uart_rx_fifo_do_read)) begin
			main_basesoc_uart_rx_fifo_level0 <= (main_basesoc_uart_rx_fifo_level0 + 1'd1);
		end
	end else begin
		if (main_basesoc_uart_rx_fifo_do_read) begin
			main_basesoc_uart_rx_fifo_level0 <= (main_basesoc_uart_rx_fifo_level0 - 1'd1);
		end
	end
	if (main_basesoc_timer_en_storage) begin
		if ((main_basesoc_timer_value == 1'd0)) begin
			main_basesoc_timer_value <= main_basesoc_timer_reload_storage;
		end else begin
			main_basesoc_timer_value <= (main_basesoc_timer_value - 1'd1);
		end
	end else begin
		main_basesoc_timer_value <= main_basesoc_timer_load_storage;
	end
	if (main_basesoc_timer_update_value_re) begin
		main_basesoc_timer_value_status <= main_basesoc_timer_value;
	end
	if (main_basesoc_timer_zero_clear) begin
		main_basesoc_timer_zero_pending <= 1'd0;
	end
	main_basesoc_timer_zero_trigger_d <= main_basesoc_timer_zero_trigger;
	if ((main_basesoc_timer_zero_trigger & (~main_basesoc_timer_zero_trigger_d))) begin
		main_basesoc_timer_zero_pending <= 1'd1;
	end
	main_bus_ack <= ((main_bus_stb & main_bus_cyc) & (~main_bus_ack));
	if (main_done) begin
		main_chaser <= {main_chaser, (~main_chaser[13])};
	end
	if (main_re) begin
		main_mode <= 1'd1;
	end
	if (main_wait) begin
		if ((~main_done)) begin
			main_count <= (main_count - 1'd1);
		end
	end else begin
		main_count <= 22'd2678571;
	end
	builder_state <= builder_next_state;
	case (builder_grant)
		1'd0: begin
			if ((~builder_request[0])) begin
				if (builder_request[1]) begin
					builder_grant <= 1'd1;
				end
			end
		end
		1'd1: begin
			if ((~builder_request[1])) begin
				if (builder_request[0]) begin
					builder_grant <= 1'd0;
				end
			end
		end
	endcase
	builder_slave_sel_r <= builder_slave_sel;
	if (builder_wait) begin
		if ((~builder_done)) begin
			builder_count <= (builder_count - 1'd1);
		end
	end else begin
		builder_count <= 20'd1000000;
	end
	builder_csr_bankarray_interface0_bank_bus_dat_r <= 1'd0;
	if (builder_csr_bankarray_csrbank0_sel) begin
		case (builder_csr_bankarray_interface0_bank_bus_adr[8:0])
			1'd0: begin
				builder_csr_bankarray_interface0_bank_bus_dat_r <= builder_csr_bankarray_csrbank0_reset0_w;
			end
			1'd1: begin
				builder_csr_bankarray_interface0_bank_bus_dat_r <= builder_csr_bankarray_csrbank0_scratch0_w;
			end
			2'd2: begin
				builder_csr_bankarray_interface0_bank_bus_dat_r <= builder_csr_bankarray_csrbank0_bus_errors_w;
			end
		endcase
	end
	if (builder_csr_bankarray_csrbank0_reset0_re) begin
		main_basesoc_reset_storage[1:0] <= builder_csr_bankarray_csrbank0_reset0_r;
	end
	main_basesoc_reset_re <= builder_csr_bankarray_csrbank0_reset0_re;
	if (builder_csr_bankarray_csrbank0_scratch0_re) begin
		main_basesoc_scratch_storage[31:0] <= builder_csr_bankarray_csrbank0_scratch0_r;
	end
	main_basesoc_scratch_re <= builder_csr_bankarray_csrbank0_scratch0_re;
	main_basesoc_bus_errors_re <= builder_csr_bankarray_csrbank0_bus_errors_re;
	builder_csr_bankarray_sel_r <= builder_csr_bankarray_sel;
	builder_csr_bankarray_interface1_bank_bus_dat_r <= 1'd0;
	if (builder_csr_bankarray_csrbank1_sel) begin
		case (builder_csr_bankarray_interface1_bank_bus_adr[8:0])
			1'd0: begin
				builder_csr_bankarray_interface1_bank_bus_dat_r <= builder_csr_bankarray_csrbank1_out0_w;
			end
		endcase
	end
	if (builder_csr_bankarray_csrbank1_out0_re) begin
		main_storage[13:0] <= builder_csr_bankarray_csrbank1_out0_r;
	end
	main_re <= builder_csr_bankarray_csrbank1_out0_re;
	builder_csr_bankarray_interface2_bank_bus_dat_r <= 1'd0;
	if (builder_csr_bankarray_csrbank2_sel) begin
		case (builder_csr_bankarray_interface2_bank_bus_adr[8:0])
			1'd0: begin
				builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_load0_w;
			end
			1'd1: begin
				builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_reload0_w;
			end
			2'd2: begin
				builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_en0_w;
			end
			2'd3: begin
				builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_update_value0_w;
			end
			3'd4: begin
				builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_value_w;
			end
			3'd5: begin
				builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_ev_status_w;
			end
			3'd6: begin
				builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_ev_pending_w;
			end
			3'd7: begin
				builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_ev_enable0_w;
			end
		endcase
	end
	if (builder_csr_bankarray_csrbank2_load0_re) begin
		main_basesoc_timer_load_storage[31:0] <= builder_csr_bankarray_csrbank2_load0_r;
	end
	main_basesoc_timer_load_re <= builder_csr_bankarray_csrbank2_load0_re;
	if (builder_csr_bankarray_csrbank2_reload0_re) begin
		main_basesoc_timer_reload_storage[31:0] <= builder_csr_bankarray_csrbank2_reload0_r;
	end
	main_basesoc_timer_reload_re <= builder_csr_bankarray_csrbank2_reload0_re;
	if (builder_csr_bankarray_csrbank2_en0_re) begin
		main_basesoc_timer_en_storage <= builder_csr_bankarray_csrbank2_en0_r;
	end
	main_basesoc_timer_en_re <= builder_csr_bankarray_csrbank2_en0_re;
	if (builder_csr_bankarray_csrbank2_update_value0_re) begin
		main_basesoc_timer_update_value_storage <= builder_csr_bankarray_csrbank2_update_value0_r;
	end
	main_basesoc_timer_update_value_re <= builder_csr_bankarray_csrbank2_update_value0_re;
	main_basesoc_timer_value_re <= builder_csr_bankarray_csrbank2_value_re;
	main_basesoc_timer_status_re <= builder_csr_bankarray_csrbank2_ev_status_re;
	if (builder_csr_bankarray_csrbank2_ev_pending_re) begin
		main_basesoc_timer_pending_r <= builder_csr_bankarray_csrbank2_ev_pending_r;
	end
	main_basesoc_timer_pending_re <= builder_csr_bankarray_csrbank2_ev_pending_re;
	if (builder_csr_bankarray_csrbank2_ev_enable0_re) begin
		main_basesoc_timer_enable_storage <= builder_csr_bankarray_csrbank2_ev_enable0_r;
	end
	main_basesoc_timer_enable_re <= builder_csr_bankarray_csrbank2_ev_enable0_re;
	builder_csr_bankarray_interface3_bank_bus_dat_r <= 1'd0;
	if (builder_csr_bankarray_csrbank3_sel) begin
		case (builder_csr_bankarray_interface3_bank_bus_adr[8:0])
			1'd0: begin
				builder_csr_bankarray_interface3_bank_bus_dat_r <= main_basesoc_uart_rxtx_w;
			end
			1'd1: begin
				builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_txfull_w;
			end
			2'd2: begin
				builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_rxempty_w;
			end
			2'd3: begin
				builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_ev_status_w;
			end
			3'd4: begin
				builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_ev_pending_w;
			end
			3'd5: begin
				builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_ev_enable0_w;
			end
			3'd6: begin
				builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_txempty_w;
			end
			3'd7: begin
				builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_rxfull_w;
			end
		endcase
	end
	main_basesoc_uart_txfull_re <= builder_csr_bankarray_csrbank3_txfull_re;
	main_basesoc_uart_rxempty_re <= builder_csr_bankarray_csrbank3_rxempty_re;
	main_basesoc_uart_status_re <= builder_csr_bankarray_csrbank3_ev_status_re;
	if (builder_csr_bankarray_csrbank3_ev_pending_re) begin
		main_basesoc_uart_pending_r[1:0] <= builder_csr_bankarray_csrbank3_ev_pending_r;
	end
	main_basesoc_uart_pending_re <= builder_csr_bankarray_csrbank3_ev_pending_re;
	if (builder_csr_bankarray_csrbank3_ev_enable0_re) begin
		main_basesoc_uart_enable_storage[1:0] <= builder_csr_bankarray_csrbank3_ev_enable0_r;
	end
	main_basesoc_uart_enable_re <= builder_csr_bankarray_csrbank3_ev_enable0_re;
	main_basesoc_uart_txempty_re <= builder_csr_bankarray_csrbank3_txempty_re;
	main_basesoc_uart_rxfull_re <= builder_csr_bankarray_csrbank3_rxfull_re;
	if (sys_rst) begin
		main_basesoc_reset_storage <= 2'd0;
		main_basesoc_reset_re <= 1'd0;
		main_basesoc_scratch_storage <= 32'd305419896;
		main_basesoc_scratch_re <= 1'd0;
		main_basesoc_bus_errors_re <= 1'd0;
		main_basesoc_bus_errors <= 32'd0;
		main_basesoc_ram_bus_ack <= 1'd0;
		serial_tx <= 1'd1;
		main_basesoc_tx_tick <= 1'd0;
		main_basesoc_rx_tick <= 1'd0;
		main_basesoc_rx_rx_d <= 1'd0;
		main_basesoc_uart_txfull_re <= 1'd0;
		main_basesoc_uart_rxempty_re <= 1'd0;
		main_basesoc_uart_tx_pending <= 1'd0;
		main_basesoc_uart_tx_trigger_d <= 1'd0;
		main_basesoc_uart_rx_pending <= 1'd0;
		main_basesoc_uart_rx_trigger_d <= 1'd0;
		main_basesoc_uart_status_re <= 1'd0;
		main_basesoc_uart_pending_re <= 1'd0;
		main_basesoc_uart_pending_r <= 2'd0;
		main_basesoc_uart_enable_storage <= 2'd0;
		main_basesoc_uart_enable_re <= 1'd0;
		main_basesoc_uart_txempty_re <= 1'd0;
		main_basesoc_uart_rxfull_re <= 1'd0;
		main_basesoc_uart_tx_fifo_readable <= 1'd0;
		main_basesoc_uart_tx_fifo_level0 <= 5'd0;
		main_basesoc_uart_tx_fifo_produce <= 4'd0;
		main_basesoc_uart_tx_fifo_consume <= 4'd0;
		main_basesoc_uart_rx_fifo_readable <= 1'd0;
		main_basesoc_uart_rx_fifo_level0 <= 5'd0;
		main_basesoc_uart_rx_fifo_produce <= 4'd0;
		main_basesoc_uart_rx_fifo_consume <= 4'd0;
		main_basesoc_timer_load_storage <= 32'd0;
		main_basesoc_timer_load_re <= 1'd0;
		main_basesoc_timer_reload_storage <= 32'd0;
		main_basesoc_timer_reload_re <= 1'd0;
		main_basesoc_timer_en_storage <= 1'd0;
		main_basesoc_timer_en_re <= 1'd0;
		main_basesoc_timer_update_value_storage <= 1'd0;
		main_basesoc_timer_update_value_re <= 1'd0;
		main_basesoc_timer_value_status <= 32'd0;
		main_basesoc_timer_value_re <= 1'd0;
		main_basesoc_timer_zero_pending <= 1'd0;
		main_basesoc_timer_zero_trigger_d <= 1'd0;
		main_basesoc_timer_status_re <= 1'd0;
		main_basesoc_timer_pending_re <= 1'd0;
		main_basesoc_timer_pending_r <= 1'd0;
		main_basesoc_timer_enable_storage <= 1'd0;
		main_basesoc_timer_enable_re <= 1'd0;
		main_basesoc_timer_value <= 32'd0;
		main_bus_ack <= 1'd0;
		main_storage <= 14'd0;
		main_re <= 1'd0;
		main_chaser <= 14'd0;
		main_mode <= 1'd0;
		main_count <= 22'd2678571;
		builder_rs232phytx_state <= 1'd0;
		builder_rs232phyrx_state <= 1'd0;
		builder_grant <= 1'd0;
		builder_slave_sel_r <= 3'd0;
		builder_count <= 20'd1000000;
		builder_csr_bankarray_sel_r <= 1'd0;
		builder_state <= 1'd0;
	end
	builder_regs0 <= serial_rx;
	builder_regs1 <= builder_regs0;
end

reg [31:0] mem[0:5135];
reg [31:0] memdat;
always @(posedge sys_clk) begin
	memdat <= mem[main_basesoc_adr];
end

assign main_basesoc_dat_r = memdat;

initial begin
	$readmemh("mem.init", mem);
end

reg [7:0] mem_1[0:62];
reg [5:0] memadr;
always @(posedge sys_clk) begin
	memadr <= builder_csr_bankarray_adr;
end

assign builder_csr_bankarray_dat_r = mem_1[memadr];

initial begin
	$readmemh("mem_1.init", mem_1);
end

reg [9:0] storage[0:15];
reg [9:0] memdat_1;
reg [9:0] memdat_2;
always @(posedge sys_clk) begin
	if (main_basesoc_uart_tx_fifo_wrport_we)
		storage[main_basesoc_uart_tx_fifo_wrport_adr] <= main_basesoc_uart_tx_fifo_wrport_dat_w;
	memdat_1 <= storage[main_basesoc_uart_tx_fifo_wrport_adr];
end

always @(posedge sys_clk) begin
	if (main_basesoc_uart_tx_fifo_rdport_re)
		memdat_2 <= storage[main_basesoc_uart_tx_fifo_rdport_adr];
end

assign main_basesoc_uart_tx_fifo_wrport_dat_r = memdat_1;
assign main_basesoc_uart_tx_fifo_rdport_dat_r = memdat_2;

reg [9:0] storage_1[0:15];
reg [9:0] memdat_3;
reg [9:0] memdat_4;
always @(posedge sys_clk) begin
	if (main_basesoc_uart_rx_fifo_wrport_we)
		storage_1[main_basesoc_uart_rx_fifo_wrport_adr] <= main_basesoc_uart_rx_fifo_wrport_dat_w;
	memdat_3 <= storage_1[main_basesoc_uart_rx_fifo_wrport_adr];
end

always @(posedge sys_clk) begin
	if (main_basesoc_uart_rx_fifo_rdport_re)
		memdat_4 <= storage_1[main_basesoc_uart_rx_fifo_rdport_adr];
end

assign main_basesoc_uart_rx_fifo_wrport_dat_r = memdat_3;
assign main_basesoc_uart_rx_fifo_rdport_dat_r = memdat_4;

SP512K #(
	.ECC_BYTE_SEL("BYTE_EN")
) SP512K (
	.AD(main_bus_adr[13:0]),
	.BYTEEN_N((~main_bus_sel[3:0])),
	.CE(1'd1),
	.CEOUT(1'd0),
	.CLK(sys_clk),
	.CS(main_cs0),
	.DI(main_datain0),
	.RSTOUT(1'd0),
	.WE(main_wren0),
	.DO(main_dataout0)
);

SP512K #(
	.ECC_BYTE_SEL("BYTE_EN")
) SP512K_1 (
	.AD(main_bus_adr[13:0]),
	.BYTEEN_N((~main_bus_sel[3:0])),
	.CE(1'd1),
	.CEOUT(1'd0),
	.CLK(sys_clk),
	.CS(main_cs1),
	.DI(main_datain1),
	.RSTOUT(1'd0),
	.WE(main_wren1),
	.DO(main_dataout1)
);

VexRiscv VexRiscv(
	.clk(sys_clk),
	.dBusWishbone_ACK(main_basesoc_dbus_ack),
	.dBusWishbone_DAT_MISO(main_basesoc_dbus_dat_r),
	.dBusWishbone_ERR(main_basesoc_dbus_err),
	.externalInterruptArray(main_basesoc_interrupt),
	.externalResetVector(main_basesoc_vexriscv),
	.iBusWishbone_ACK(main_basesoc_ibus_ack),
	.iBusWishbone_DAT_MISO(main_basesoc_ibus_dat_r),
	.iBusWishbone_ERR(main_basesoc_ibus_err),
	.reset((sys_rst | main_basesoc_reset)),
	.softwareInterrupt(1'd0),
	.timerInterrupt(1'd0),
	.dBusWishbone_ADR(main_basesoc_dbus_adr),
	.dBusWishbone_BTE(main_basesoc_dbus_bte),
	.dBusWishbone_CTI(main_basesoc_dbus_cti),
	.dBusWishbone_CYC(main_basesoc_dbus_cyc),
	.dBusWishbone_DAT_MOSI(main_basesoc_dbus_dat_w),
	.dBusWishbone_SEL(main_basesoc_dbus_sel),
	.dBusWishbone_STB(main_basesoc_dbus_stb),
	.dBusWishbone_WE(main_basesoc_dbus_we),
	.iBusWishbone_ADR(main_basesoc_ibus_adr),
	.iBusWishbone_BTE(main_basesoc_ibus_bte),
	.iBusWishbone_CTI(main_basesoc_ibus_cti),
	.iBusWishbone_CYC(main_basesoc_ibus_cyc),
	.iBusWishbone_DAT_MOSI(main_basesoc_ibus_dat_w),
	.iBusWishbone_SEL(main_basesoc_ibus_sel),
	.iBusWishbone_STB(main_basesoc_ibus_stb),
	.iBusWishbone_WE(main_basesoc_ibus_we)
);

OSCA #(
	.HF_CLK_DIV("6"),
	.HF_OSC_EN("ENABLED")
) OSCA (
	.HFOUTEN(1'd1),
	.HFCLKOUT(sys_clk)
);

/*
PLL #(
	.BW_CTL_BIAS("0b1111"),
	.CLKMUX_FB("CMUX_CLKOS5"),
	.CRIPPLE("3P"),
	.CSET("8P"),
	.DELA("10"),
	.DELF("32"),
	.DIVA("10"),
	.DIVF("32"),
	.ENCLK_CLKOP("ENABLED"),
	.ENCLK_CLKOS5("ENABLED"),
	.FBK_INTEGER_MODE("ENABLED"),
	.FBK_MASK("0b00000000"),
	.FBK_MMD_DIG("1"),
	.IPI_CMP("0b1100"),
	.IPI_CMPN("0b0011"),
	.IPP_CTRL("0b0110"),
	.IPP_SEL("0b1111"),
	.KP_VCO("0b00011"),
	.PHIA("0"),
	.PLLPD_N("USED"),
	.PLLRESET_ENA("ENABLED"),
	.REF_INTEGER_MODE("ENABLED"),
	.REF_MMD_DIG("1"),
	.SEL_FBK("FBKCLK5"),
	.V2I_1V_EN("ENABLED"),
	.V2I_KVCO_SEL("60"),
	.V2I_PP_ICTRL("0b11111"),
	.V2I_PP_RES("10K")
) PLL_0 (
	.FBKCK(builder_clkfb),
	.PLLRESET(main_crg_reset),
	.REFCK(main_crg_clkin),
	.CLKOP(sys_clk),
	.CLKOS5(builder_clkfb),
	.LOCK(main_crg_locked)
);
*/

FD1P3BX FD1P3BX(
	.CK(por_clk),
	.D(1'd0),
	.PD((~gsrn)),
	.SP(1'd1),
	.Q(builder_rst10)
);

FD1P3BX FD1P3BX_1(
	.CK(por_clk),
	.D(builder_rst10),
	.PD((~gsrn)),
	.SP(1'd1),
	.Q(por_rst)
);

FD1P3BX FD1P3BX_2(
	.CK(sys_clk),
	.D(1'd0),
	.PD(((~main_crg_locked) | (~main_crg_por_done))),
	.SP(1'd1),
	.Q(builder_rst11)
);

FD1P3BX FD1P3BX_3(
	.CK(sys_clk),
	.D(builder_rst11),
	.PD(((~main_crg_locked) | (~main_crg_por_done))),
	.SP(1'd1),
	.Q(sys_rst)
);

endmodule
