# Clock Signal
set_property LOC W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# UART tx and
set_property LOC A18 [get_ports ser_tx]
set_property LOC B18 [get_ports ser_rx]
set_property IOSTANDARD LVCMOS33 [get_ports ser_tx]
set_property IOSTANDARD LVCMOS33 [get_ports ser_rx]

# Switches
set_property LOC V17 [get_ports {sw[0]}]
set_property LOC V16 [get_ports {sw[1]}]
set_property LOC W16 [get_ports {sw[2]}]
set_property LOC W17 [get_ports {sw[3]}]
set_property LOC W15 [get_ports {sw[4]}]
set_property LOC V15 [get_ports {sw[5]}]
set_property LOC W14 [get_ports {sw[6]}]
set_property LOC W13 [get_ports {sw[7]}]
set_property LOC V2  [get_ports {sw[8]}]
set_property LOC T3  [get_ports {sw[9]}]
set_property LOC T2  [get_ports {sw[10]}]
set_property LOC R3  [get_ports {sw[11]}]
set_property LOC W2  [get_ports {sw[12]}]
set_property LOC U1  [get_ports {sw[13]}]
set_property LOC T1  [get_ports {sw[14]}]
set_property LOC R2  [get_ports {sw[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]
# Leds
set_property LOC U16 [get_ports {led[0]}]
set_property LOC E19 [get_ports {led[1]}]
set_property LOC U19 [get_ports {led[2]}]
set_property LOC V19 [get_ports {led[3]}]
set_property LOC W18 [get_ports {led[4]}]
set_property LOC U15 [get_ports {led[5]}]
set_property LOC U14 [get_ports {led[6]}]
set_property LOC V14 [get_ports {led[7]}]
set_property LOC V13 [get_ports {led[8]}]
set_property LOC V3  [get_ports {led[9]}]
set_property LOC W3  [get_ports {led[10]}]
set_property LOC U3  [get_ports {led[11]}]
set_property LOC P3  [get_ports {led[12]}]
set_property LOC N3  [get_ports {led[13]}]
set_property LOC P1  [get_ports {led[14]}]
set_property LOC L1  [get_ports {led[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
