/*
 * Generated by harness_gen.py
 * From: picosoc_def.v
 */
module top(input wire clk, input wire stb, input wire di, output wire do);
    localparam integer DIN_N = 42;
    localparam integer DOUT_N = 80;

    reg [DIN_N-1:0] din;
    wire [DOUT_N-1:0] dout;

    reg [DIN_N-1:0] din_shr;
    reg [DOUT_N-1:0] dout_shr;

    always @(posedge clk) begin
        din_shr <= {din_shr, di};
        dout_shr <= {dout_shr, din_shr[DIN_N-1]};
        if (stb) begin
            din <= din_shr;
            dout_shr <= dout;
        end
    end

    assign do = dout_shr[DOUT_N-1];
    picosoc dut(
            .clk(clk),
            .resetn(din[0]),
            .iomem_valid(dout[0]),
            .iomem_ready(din[1]),
            .iomem_wstrb(dout[4:1]),
            .iomem_addr(dout[36:5]),
            .iomem_wdata(dout[68:37]),
            .iomem_rdata(din[33:2]),
            .irq_5(din[34]),
            .irq_6(din[35]),
            .irq_7(din[36]),
            .ser_tx(dout[69]),
            .ser_rx(din[37]),
            .flash_csb(dout[70]),
            .flash_clk(dout[71]),
            .flash_io0_oe(dout[72]),
            .flash_io1_oe(dout[73]),
            .flash_io2_oe(dout[74]),
            .flash_io3_oe(dout[75]),
            .flash_io0_do(dout[76]),
            .flash_io1_do(dout[77]),
            .flash_io2_do(dout[78]),
            .flash_io3_do(dout[79]),
            .flash_io0_di(din[38]),
            .flash_io1_di(din[39]),
            .flash_io2_di(din[40]),
            .flash_io3_di(din[41])
            );
endmodule
