set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports jtag_clk]
set_property IOSTANDARD LVCMOS33 [get_ports io_G15]
set_property IOSTANDARD LVCMOS33 [get_ports io_G16]
set_property IOSTANDARD LVCMOS33 [get_ports io_F15]
set_property IOSTANDARD LVCMOS33 [get_ports io_B12]
set_property IOSTANDARD LVCMOS33 [get_ports io_B10]
set_property IOSTANDARD LVCMOS33 [get_ports {io_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_led[7]}]

