name: CI tests

on: [push, pull_request]

jobs:

  Run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    steps:

    - uses: actions/checkout@v3.0.2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check formatting
      run: |
        pip install yapf==0.31.0
        make format
        test $(git status --porcelain | wc -l) -eq 0 || { git diff; false;  }

    - name: Check license
      run: source .github/workflows/scripts/check_license.sh

    - name: Check python scripts
      run: source .github/workflows/scripts/check_python_scripts.sh

    - name: Prepare env
      run: |
        make env
        make install_symbiflow

    - name: Run tests
      run: |
        source env.sh
        # Testing parameters injection feature
        python3 exhaust.py --parameters parameters.yaml --toolchain vpr --project blinky --build_type parameters --only_required --fail
        # Testing multiple samples
        python3 exhaust.py --build_type multiple-samples --run_config run_configs/multiple_samples.yaml --only_required --fail
        # Testing multiple seeds
        python3 exhaust.py --build_type multiple-seeds --run_config run_configs/multiple_seeds.yaml --only_required --fail

